#!/bin/sh

cd ~
mkdir -p /etc/nginx/conf
download_echbay_nginx_config(){
wget --no-check-certificate -q "https://echbay.com/server/conf/index.php?file=$1&download=1&rand=1" -O /etc/nginx/conf/$1.conf ; chmod 600 /etc/nginx/conf/$1.conf
}
#download_echbay_nginx_config "ddos1"
#download_echbay_nginx_config "ddos2"
#download_echbay_nginx_config "ssl"
download_echbay_nginx_config "all"
download_echbay_nginx_config "block"
download_echbay_nginx_config "staticfiles"
download_echbay_nginx_config "drop"
service nginx restart
