#!/bin/sh
cd ~
if [ -d /opt/echbay_vpssim ]; then
	rm -rf /opt/echbay_vpssim/*
	rm -rf /opt/echbay_vpssim
	sleep 5
fi

sudo yum -y install git
git clone https://github.com/itvn9online/vpssim-free /opt/echbay_vpssim
sleep 5

find /opt/echbay_vpssim/script/vpssim/menu -type f -exec chmod 755 {} \;
yes | cp -rf /opt/echbay_vpssim/version /opt/echbay_vpssim/script/vpssim/vpssim.newversion

cd /opt/echbay_vpssim
chmod +x setup
bash setup
