#!/bin/sh

cd ~
if [ -d /opt/echbay_vpssim ]; then
rm -rf /opt/echbay_vpssim/*
rm -rf /opt/echbay_vpssim
sleep 2
fi

sudo yum -y install wget

#
cd ~
wget --no-check-certificate -q https://raw.githubusercontent.com/itvn9online/vpssim-free/master/script/vpssim/menu/git-clone
chmod +x /root/git-clone
bash /root/git-clone

cd /opt/echbay_vpssim
chmod +x setup
bash setup
