#!/bin/sh
cd ~
if [ -d /opt/echbay_vpssim ]; then
	rm -rf /opt/echbay_vpssim/*
	rm -rf /opt/echbay_vpssim
fi

yum -y install git
git clone https://github.com/itvn9online/vpssim-free /opt/echbay_vpssim

cd /opt/echbay_vpssim ; chmod +x setup ; bash setup
