#!/bin/sh

if [ $(id -u) != "0" ]; then
    echo "Co loi: Ban phai dang nhap bang user root!"
    exit
fi

if [ -f /var/cpanel/cpanel.config ]; then
echo "Server cua ban da cai san WHM/Cpanel, neu ban muon dung ECHBAY-VPSSIM"
echo "Hay cai moi lai he dieu hanh, khuyen dung centos6 - 64bit"
echo "Chao tam biet !"
exit
fi

if [ -f /etc/psa/.psa.shadow ]; then
echo "Server cua ban da cai san Plesk, neu ban muon dung ECHBAY-VPSSIM"
echo "Hay cai moi lai he dieu hanh, khuyen dung centos6 - 64bit"
echo "Chao tam biet !"
exit
fi

if [ -f /etc/init.d/directadmin ]; then
echo "Server cua ban da cai san DirectAdmin, neu ban muon dung ECHBAY-VPSSIM"
echo "Hay cai moi lai he dieu hanh, khuyen dung centos6 - 64bit"
echo "Chao tam biet !"
exit
fi

if [ -f /etc/init.d/webmin ]; then
echo "Server cua ban da cai san webmin, neu ban muon dung ECHBAY-VPSSIM"
echo "Hay cai moi lai he dieu hanh, khuyen dung centos6 - 64bit"
echo "Chao tam biet !"
exit
fi

if [ -f /home/vpssim.conf ]; then
clear
echo "========================================================================="
echo "========================================================================="
echo "Server/VPS cua ban da cai san ECHBAY-VPSSIM"
echo "Hay su dung lenh ECHBAY-VPSSIM de truy cap ECHBAY-VPSSIM menu"
echo "Chao tam biet !"
echo "========================================================================="
echo "========================================================================="
rm -rf install*
exit
fi

arch=`uname -m`
if [ ! "$arch" = "x86_64" ]; then
clear
echo "========================================================================="
echo "========================================================================="
echo "Hien tai! ECHBAY-VPSSIM chi ho tro phien ban x64 bit"
echo "Vui long cai dat phien ban he dieu hanh x86_64 roi thu lai"
echo "Chao tam biet !"
echo "========================================================================="
echo "========================================================================="
rm -rf install*
exit
fi

if [ -f /etc/yum.repos.d/epel.repo ]; then
sudo sed -i "s/mirrorlist=https/mirrorlist=http/" /etc/yum.repos.d/epel.repo
fi

#wget -q https://vpssim.echbay.com/script/vpssim/calc -O /bin/calc && chmod +x /bin/calc
yes | cp -rf /opt/echbay_vpssim/script/vpssim/calc /bin/calc && chmod +x /bin/calc
clear  
rm -rf /root/vpssim*

#prompt="Nhap lua chon cua ban: "
#options=("Tieng Viet" "Tieng Anh" "Huy Bo")
echo "========================================================================="
echo "ECHBAY-VPSSIM Ho Tro Centos 6 & Centos 7 & Centos 8 x64"
echo "-------------------------------------------------------------------------"
echo "Ban nen su dung Centos 7 x64 de Server co hieu suat tot nhat."
echo "-------------------------------------------------------------------------"
#echo "ECHBAY-VPSSIM ho tro 2 ngon ngu: Tieng Anh va Tieng Viet. "
#echo "-------------------------------------------------------------------------"
#echo "Trong qua trinh su dung, ban co the thay doi ngon ngu ngon ngu bang chuc "
#echo "-------------------------------------------------------------------------"
#echo "nang [ Change ECHBAY-VPSSIM Language ] trong [ Update System ]."
#echo "========================================================================="
#echo "                   Chon Ngon Ngu Cho ECHBAY-VPSSIM"
echo "========================================================================="

#PS3="$prompt"
#select opt in "${options[@]}"; do 
#case "$REPLY" in
#1) yourlanguage="vietnamese"; break;;
#2) yourlanguage="english"; break;;
#3) yourlanguage="Cancel"; break;;
#*) echo "Ban nhap sai, vui long nhap theo so thu tu trong danh sach";continue;;
#esac  
#done
yourlanguage="vietnamese"

current_os_version=$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))
#echo $current_os_version

cd ~

if [ "$yourlanguage" = "english" ]; then
echo "----------------------------------------------------------------------------"
echo "Please wait ..."
sleep 2
#wget -q --no-check-certificate https://vpssim.com/script/vpssim/centos${current_os_version}/vpssim-setup && chmod +x vpssim-setup && clear && ./vpssim-setup
#wget -q --no-check-certificate https://vpssim.echbay.com/script/vpssim/centos${current_os_version}/vpssim-setup && chmod +x vpssim-setup && clear && ./vpssim-setup
cd /opt/echbay_vpssim/script/vpssim/centos${current_os_version} ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
yes | cp -rf /opt/echbay_vpssim/script/vpssim/centos${current_os_version}/vpssim-setup ~/vpssim-setup ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
elif [ "$yourlanguage" = "vietnamese" ]; then
echo "----------------------------------------------------------------------------"
echo "Please wait ..."
sleep 2
#wget -q --no-check-certificate https://vpssim.echbay.com/script/vpssim/centos${current_os_version}/vpssim-setup && chmod +x vpssim-setup && clear && ./vpssim-setup
if [ "$current_os_version" == "6" ]; then
#cd /opt/echbay_vpssim/script/vpssim/centos6 ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
yes | cp -rf /opt/echbay_vpssim/script/vpssim/centos6/vpssim-setup ~/vpssim-setup ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
elif [ "$current_os_version" == "7" ]; then
#cd /opt/echbay_vpssim/script/vpssim/centos7 ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
yes | cp -rf /opt/echbay_vpssim/script/vpssim/centos7/vpssim-setup ~/vpssim-setup ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
else
#cd /opt/echbay_vpssim/script/vpssim/centos8 ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
yes | cp -rf /opt/echbay_vpssim/script/vpssim/centos8/vpssim-setup ~/vpssim-setup ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
fi
else 
rm -rf /root/install* && rm -rf /root/vpssim* && clear
fi


