#!/bin/sh
prompt="Nhap lua chon cua ban (5-Thoat):"
options=("Them Crontab" "Xoa 1 Crontab" "Xoa Tat Ca Crontab" "List Crontab" "Thoat")
printf "=========================================================================\n"
printf "                VPSSIM - Quan Ly VPS/Server by HostingAZ.VN \n"
printf "=========================================================================\n"
printf "                              Quan Ly Cronjob \n"
echo "========================================================================="
if [ ! -f /var/spool/cron/root ]; then
printf "                           Crontab running: 0 \n"
else
printf "                           Crontab running: $(wc -l /var/spool/cron/root | awk '{print $1}') \n"
fi
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1 ) /etc/vpssim/menu/crontab/vpssim-them-cronjob;;
    2 ) /etc/vpssim/menu/crontab/vpssim-xoa-mot-crontab;;
    3 ) /etc/vpssim/menu/crontab/vpssim-befor-xoa-het-cronjob;;
    4 ) /etc/vpssim/menu/crontab/vpssim-crontab-hien-tai;;
    5 ) clear && /bin/vpssim;;
    
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu";continue;;

    esac
done

