#!/bin/sh

if [ ! -f /etc/vpssim/minfreedisc.info ]; then
echo "1000" > /etc/vpssim/minfreedisc.info
fi

minfreedisc=`cat /etc/vpssim/minfreedisc.info`
#echo "minfreedisc: "$minfreedisc

if ! [[ $minfreedisc =~ $checktruenumber ]] ; then
echo "1000" > /etc/vpssim/minfreedisc.info
fi 
if [ ! -f /tmp/checkdiscsize ]; then
touch -a -m -t 201602180130.09 /tmp/checkdiscsize 
fi
fileTime3=$(date -r /tmp/checkdiscsize +%d)
if [ ! "$fileTime3" == "$curTime" ]; then
touch /tmp/checkdiscsize
disfree=$(calc $(df $PWD | awk '/[0-9]%/{print $(NF-2)}')/1024)
echo "diskfree: "$disfree

if [[ $disfree =~ $checktruenumber ]] ; then  
if [ "$disfree" -lt "$minfreedisc" ]; then
echo "========================================================================="
echo "CANH BAO: Hien tai server con $disfree MB dung luong trong ! "
fi
fi
fi



