#!/bin/bash

prompt="Vui long chon/ Please choose (0-Backspace):"
options=( "Website & Code"  "List Website in Server")

printf "=========================================================================\n"
printf "                            Account Manager\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in

	1) clear && /etc/vpssim/menu/centos9/option/them-website-menu;;
    2) clear && /etc/vpssim/menu/centos9/option/list-website-tren-vps;;
    0) clear && vpssim;;
    *) echo "Vui long chon theo danh sach/ Please choose from the list"; continue;;

    esac

done
