#!/bin/bash


#
/etc/vpssim/menu/centos9/inc/list-website-tren-vps-before

#
echo "========================================================================="
echo "Nhap vao ten mien se su dung database nay"
echo "-------------------------------------------------------------------------"
echo "Enter domain for this database"
echo "-------------------------------------------------------------------------"

echo -n "Nhap ten website [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`

#
re='^[0-9]+$'
# nếu người dùng nhập vào là 1 số
if [[ $website =~ $re ]] ; then
    # xem số này có chứa thông tin tên miền tương ứng không
    if [ -f "/tmp/domain_number$website.txt" ]; then
    # có thì lấy tên miền trong file
    website=`cat /tmp/domain_number$website.txt`
    fi
fi

#
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "Ten mien trong/ Domain is empty!"
/etc/vpssim/menu/centos9/option/them-website-menu
exit
fi

#
/etc/vpssim/menu/centos9/inc/add-database $website
