#!/bin/bash


#
/etc/vpssim/menu/centos9/inc/list-website-tren-vps-before

#
echo "========================================================================="
echo "Chon ten mien su dung database nay/ Choose domain for this database"
echo "-------------------------------------------------------------------------"

echo -n "Chon ten mien chinh/ Choose primary domain [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`

#
if [ "$website" = "" ]; then
clear
/etc/vpssim/menu/centos9/option/account-manager-menu
exit
fi

# xem số này có chứa thông tin tên miền tương ứng không
if [ -f "/tmp/domain_number$website.txt" ]; then
# có thì lấy tên miền trong file
website=`cat /tmp/domain_number$website.txt`
echo "Ten mien chinh/ Primary domain: "$website
else
clear
echo "========================================================================="
echo "Vui long chon lai/ Please choose again!"
echo "-------------------------------------------------------------------------"
/etc/vpssim/menu/centos9/option/add-database-before
exit
fi

#
/etc/vpssim/menu/centos9/inc/add-database $website
exit
