#!/bin/bash

prompt="Vui long chon/ Please choose (0-Backspace):"
options=( "Redis Cache" "Memcached" "Varnish cache" )

printf "=========================================================================\n"
printf "                            Cache\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in

    1) clear && /etc/vpssim/menu/centos9/option/redis-cache;;
    2) clear && /etc/vpssim/menu/centos9/option/memcached;;
    3) clear && /etc/vpssim/menu/centos9/option/varnish-cache;;
    0) clear && vpssim;;
    *) echo "Vui long chon theo danh sach/ Please choose from the list"; continue;;

    esac

done

#
exit
