#!/bin/bash
. /home/vpssim.conf

# kiểm tra và cài đặt FTP nếu chưa có
/etc/vpssim/menu/centos9/inc/ftpserver-menu-before

#
if [ ! -f /etc/pure-ftpd/pureftpd.passwd ]; then
touch /etc/pure-ftpd/pureftpd.passwd
fi

#
prompt="Lua chon cua ban (0-Backspace):"
options=("Create FTP account" "Change FTP password" "View FTP password" )
printf "=========================================================================\n"
printf "                VPSSIM - Quan Ly VPS/ Server by EchBay.com \n"
printf "=========================================================================\n"
printf "                            Quan Ly FTP Server \n"
printf "=========================================================================\n"
echo ""

#
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
        1) /etc/vpssim/menu/centos9/option/tao-ftp-user-cho-domain;;
        2) /etc/vpssim/menu/centos9/option/thay-mat-khau-user-ftp;;
        3) /etc/vpssim/menu/centos9/option/view-userftp-password;;
        0) clear && /etc/vpssim/menu/centos9/option/them-website-menu;;
        *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done


