#!/bin/bash
. /home/vpssim.conf

#
/etc/vpssim/menu/centos9/option/ftpserver-menu-before

#
if [ ! -f /etc/pure-ftpd/pureftpd.passwd ]; then
touch /etc/pure-ftpd/pureftpd.passwd
fi

#
prompt="Lua chon cua ban (0-Thoat):"
options=("Tao Tai Khoan FTP Cho Website" "Vo Hieu Hoa Tai Khoan FTP" "Thay Mat Khau Tai Khoan FTP" "Xem Thong Tin FTP Cua Website" )
printf "=========================================================================\n"
printf "                VPSSIM - Quan Ly VPS/ Server by EchBay.com \n"
printf "=========================================================================\n"
printf "                            Quan Ly FTP Server \n"
printf "=========================================================================\n"
echo ""
PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
        1) /etc/vpssim/menu/centos9/option/tao-ftp-user-cho-domain;;
        2) /etc/vpssim/menu/vpssim-xoa-ftp-user;;
        3) /etc/vpssim/menu/vpssim-thay-mat-khau-user-ftp;;
        4) /etc/vpssim/menu/vpssim-view-userftp-password;;
        0) clear && vpssim;;
        *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done


