#!/bin/bash

#
clear
echo "========================================================================="
echo "Confirm reset MySQL root password? Please choose [y] for continue..."
echo -n "Ban co muon khoi tao lai mat khau root cho MySQL khong? [y/N] "
read resetOk

#
if [ "$resetOk" = "y" ] || [ "$resetOk" = "Y" ]; then

#
passrootmysql=`date |md5sum |cut -c '1-16'`
#echo "$passrootmysql" > /tmp/vpssim-mysqlrootpass

#
mysqladmin -u root password "$passrootmysql"

# thay thông tin mới để người dùng truy cập vào xem status
if [ -f /home/VPSSIM-manage-info.txt ]; then
sed -i "s/MySQL root password: .*/MySQL root password: ${passrootmysql}/g" /home/VPSSIM-manage-info.txt
fi
sed -i "s/mariadbpass=.*/mariadbpass=\"${passrootmysql}\"/g" /home/vpssim.conf

# hiển thị thông tin
clear
#echo "========================================================================="
if [ -f /home/VPSSIM-manage-info.txt ]; then
cat /home/VPSSIM-manage-info.txt
fi

fi

#
/etc/vpssim/menu/centos9/option/security-firewall-menu
exit
