#!/bin/bash
. /home/vpssim.conf

#
/etc/vpssim/menu/centos9/inc/list-website-tren-vps-before

if [ "$1" = "" ]; then
echo "========================================================================="
echo "Su dung chuc nang nay de thay mat khau tai khoan FTP cua website"
echo "-------------------------------------------------------------------------"
echo -n "Nhap ten website [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`

#
re='^[0-9]+$'
# nếu người dùng nhập vào là 1 số
if [[ $website =~ $re ]] ; then
    # xem số này có chứa thông tin tên miền tương ứng không
    if [ -f "/tmp/domain_number$website.txt" ]; then
    # có thì lấy tên miền trong file
    website=`cat /tmp/domain_number$website.txt`
    echo "Ten mien/ Domain: "$website
    fi
fi
else
website=$1
fi

#
/etc/vpssim/menu/centos9/inc/ftpserver-menu-validate $website

if [ "$(pure-pw list | grep "/home/$website/")" == "" ]; then
clear
echo "========================================================================="
echo "Website $website chua tao tai khoan FTP!"
/etc/vpssim/menu/centos9/option/ftpserver-menu
exit
fi

#
username=$(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}')

#
echo "========================================================================="
echo "Phat hien tai khoan FTP cho $website" 
echo "-------------------------------------------------------------------------"
echo "Thong tin tai khoan FTP hien tai:"
echo "-------------------------------------------------------------------------"
echo "Username: $username | Password: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $10}')"
echo "-------------------------------------------------------------------------"
echo "Bay gio VPSSIM se thay mat khau moi cho: $username"
echo "========================================================================="
echo "Please wait..."

# xác định ftp account trong file lưu trữ
mkmoi=`date |md5sum |cut -c '1-16'`
#echo "$mkmoi" | passwd --stdin $ftpuser
( echo ${mkmoi} ; echo ${mkmoi} ) | pure-pw passwd $username
pure-pw mkdb

#
cat > "/tmp/xoaftpuser" <<END	
sed -i '/\/home\/$website/d' /etc/vpssim/FTP-Account.info
END
chmod +x /tmp/xoaftpuser
/tmp/xoaftpuser
rm -rf /tmp/xoaftpuser

#
/etc/vpssim/menu/centos9/inc/ftp-password-after $website $username $mkmoi

#
/etc/vpssim/menu/centos9/option/ftpserver-menu
exit
