#!/bin/bash

#
echo "========================================================================="
echo "Coming soon..."
echo "-------------------------------------------------------------------------"

#
/etc/vpssim/menu/centos9/option/security-firewall-menu
exit
