#!/bin/bash
. /home/vpssim.conf

#
/etc/vpssim/menu/centos9/inc/list-website-tren-vps-before

#
create_tmp=$2

#
if [ ! "$1" = "" ]; then
website=$1
else
    echo "========================================================================="
    echo "Su dung chuc nang nay de tao FTP user cho  website"
    echo "-------------------------------------------------------------------------"
    echo -n "Nhap website ban muon tao tai khoan FTP/ Enter FTP website [ENTER]: " 
    read website
    website=`echo $website | tr '[A-Z]' '[a-z]'`

    #
    re='^[0-9]+$'
    # nếu người dùng nhập vào là 1 số
    if [[ $website =~ $re ]] ; then
        # xem số này có chứa thông tin tên miền tương ứng không
        if [ -f "/tmp/domain_number$website.txt" ]; then
        # có thì lấy tên miền trong file
        website=`cat /tmp/domain_number$website.txt`
        echo "Ten mien/ Domain: "$website
        fi
    fi
fi

#
/etc/vpssim/menu/centos9/inc/ftpserver-menu-validate $website

if [ ! -f /etc/pure-ftpd/pureftpd.passwd ]; then
touch /etc/pure-ftpd/pureftpd.passwd
fi

if [ ! "$(pure-pw list | grep "/home/$website/")" == "" ]; then
clear
echo "========================================================================="
echo "Ban da tao tai khoan FTP cho $website" 
echo "-------------------------------------------------------------------------"
echo "Thong tin tai khoan FTP:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip "
echo "-------------------------------------------------------------------------"
echo "User: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}') | Password: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $10}')"
if [ ! "$create_tmp" = "" ]; then
/etc/vpssim/menu/centos9/option/ftpserver-menu
fi
fi


echo "-------------------------------------------------------------------------"
echo "Tim thay $website tren he thong"
echo "-------------------------------------------------------------------------"
echo "$website chua tao tai khoan FTP"
echo "-------------------------------------------------------------------------"
echo "VPSSIM se tao tai khoan FTP cho $website ngay bay gio"
echo "-------------------------------------------------------------------------"
echo "Please wait...";


#echo "$website" > /tmp/vpssimftp.txt
#sed -i 's/\.//g' /tmp/vpssimftp.txt
#sed -i 's/\-//g' /tmp/vpssimftp.txt
#username=`cat /tmp/vpssimftp.txt | sed "s/\_//" | sed "s/\_//" | sed "s/\_//" | sed "s/\_//" | cut -c1-30`
username="ftp@"$website
password=`date |md5sum |cut -c '1-16'`
#useradd -m -d /home/$website -g nginx -p $password $username
#usermod -aG nginx $username
#chmod g+rxw /home/$website
( echo ${password} ; echo ${password} ) | pure-pw useradd $username -u nginx -g nginx -d /home/$website -m 
pure-pw mkdb
rm -rf /tmp/ftpvpssim.temp;
pure-pw mkdb

if [ ! -f /etc/vpssim/FTP-Account.info ]; then
echo "=========================================================================" > /etc/vpssim/FTP-Account.info
echo "Please Do Not Delete This File " >> /etc/vpssim/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/vpssim/FTP-Account.info
echo "If you delete this file, VPSSIM will not run !" >> /etc/vpssim/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/vpssim/FTP-Account.info
echo "All FTP User for all domain on VPS list below:" >> /etc/vpssim/FTP-Account.info
echo "=========================================================================" >> /etc/vpssim/FTP-Account.info
echo "" >> /etc/vpssim/FTP-Account.info
fi

################
echo "FTP Account for $website | Username: $username | Password: $password | dd /home/$website/ " >> /etc/vpssim/FTP-Account.info
clear
echo "=========================================================================" 
echo "Tao tai khoan FTP cho $website thanh cong"
echo "-------------------------------------------------------------------------"
echo "Thong tin login:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip "
echo "-------------------------------------------------------------------------"
echo "User: $username | Password: $password"

# lưu thông tin database để quá trình tạo website wordpress có cái mà sử dụng luôn
if [ ! "$create_tmp" = "" ]; then
echo "$username" > /tmp/vpssim-lastftp.txt
echo "$password" > /tmp/vpssim-lastpassftp.txt
else
/etc/vpssim/menu/centos9/option/ftpserver-menu
fi
