#!/bin/bash
. /home/vpssim.conf

#
/etc/vpssim/menu/centos9/inc/list-website-tren-vps-before

if [ "$1" = "" ]; then
echo "========================================================================="
echo "Su dung chuc nang nay de thay mat khau tai khoan FTP cua website"
echo "-------------------------------------------------------------------------"
echo -n "Nhap ten website [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`

#
re='^[0-9]+$'
# nếu người dùng nhập vào là 1 số
if [[ $website =~ $re ]] ; then
# xem số này có chứa thông tin tên miền tương ứng không
if [ -f "/tmp/domain_number$website.txt" ]; then
# có thì lấy tên miền trong file
website=`cat /tmp/domain_number$website.txt`
fi
fi
else
website=$1
fi

#
/etc/vpssim/menu/centos9/inc/ftpserver-menu-validate $website

if [ "$(pure-pw list | grep "/home/$website/")" == "" ]; then
clear
echo "========================================================================="
echo "Website $website chua tao tai khoan FTP!"
/etc/vpssim/menu/centos9/option/ftpserver-menu
fi

echo "========================================================================="
echo "Phat hien tai khoan FTP cho $website" 
echo "-------------------------------------------------------------------------"
echo "Thong tin tai khoan FTP hien tai:"
echo "-------------------------------------------------------------------------"
echo "Username: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}')  |  Password: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $10}')"
echo "-------------------------------------------------------------------------"
echo "Bay gio VPSSIM se thay mat khau moi cho: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}')"
echo "========================================================================="
echo "Please wait ....."

# xác định ftp account trong file lưu trữ
username=$(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}')
mkmoi=`date |md5sum |cut -c '1-16'`
#echo "$mkmoi" | passwd --stdin $ftpuser
( echo ${mkmoi} ; echo ${mkmoi} ) | pure-pw passwd $username
pure-pw mkdb

cat > "/tmp/xoaftpuser" <<END	
sed -i '/\/home\/$website/d' /etc/vpssim/FTP-Account.info
END
chmod +x /tmp/xoaftpuser
/tmp/xoaftpuser
rm -rf /tmp/xoaftpuser

echo "FTP Account for $website | Username: $username | Password: $mkmoi | dd /home/$website/ " >> /etc/vpssim/FTP-Account.info
clear
echo "========================================================================= "
echo "Thay mat khau tai khoan FTP cua $website thanh cong"
echo "-------------------------------------------------------------------------"
echo "Thong tin login moi:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip"
echo "-------------------------------------------------------------------------"
echo "User: $username | Password: $mkmoi"

#
/etc/vpssim/menu/centos9/option/ftpserver-menu
