#!/bin/bash 
. /home/vpssim.conf

#
cd ~

#
echo "========================================================================="
echo "Su dung chuc nang nay de them website vao server"
echo "-------------------------------------------------------------------------"
echo -n "Nhap ten mien/ Enter your domain [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`

if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "Vui long nhap ten mien/ Please enter your domain!"
/etc/vpssim/menu/centos9/option/them-website-menu
exit
fi

kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,12}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website khong dung dinh dang duoc ho tro/ Domain format error!!"
echo "-------------------------------------------------------------------------"
echo "Vui long thu lai/ Please try again!"
/etc/vpssim/menu/centos9/option/them-website-menu
exit
fi

if [ -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Ten mien da ton tai/ Domain exist! "$website
/etc/vpssim/menu/centos9/option/them-website-menu
exit
fi

#
mkdir -p "/home/$website/public_html"
mkdir -p "/home/$website/logs"
chmod 777 "/home/$website/logs"

#
yes | cp /etc/vpssim/menu/centos9/option/tmp/index.php "/home/$website/public_html/index.php"
yes | cp /etc/vpssim/menu/centos9/option/tmp/robots.txt "/home/$website/public_html/index.php"

#
chown -R nginx:nginx "/home/$website/public_html/"
find "/home/$website/public_html/" -type d -exec chmod g+s {} \;

#
yes | cp /etc/vpssim/menu/centos9/option/tmp/domain_vhost.txt "/etc/nginx/conf.d/$website.conf"
# thay domain trong file vhost
cat > "/tmp/vpssimSetConfigFile" <<END
#!/bin/bash 
sed -i 's/\%website\%/$website/g' "/etc/nginx/conf.d/$website.conf"
END
chmod +x /tmp/vpssimSetConfigFile
sh /tmp/vpssimSetConfigFile
rm -f /tmp/vpssimSetConfigFile

#
if [ ! -d /etc/vpssim/errorpage_html ]; then
	if [ -d /opt/echbay_vpssim/script/vpssim/errorpage_html ]; then
		mkdir -p /etc/vpssim/errorpage_html ; chmod 755 /etc/vpssim/errorpage_html
		yes | cp -rf /opt/echbay_vpssim/script/vpssim/errorpage_html/. /etc/vpssim/errorpage_html/
	fi
fi

mkdir -p /home/$website/errorpage_html && cp -r /etc/vpssim/errorpage_html/*.html /home/$website/errorpage_html


#
echo "-------------------------------------------------------------------------"
echo -n "Ban co muon VPSSIM tao Database moi cho $website ? [y/N] " 
read response

#
if [ "$response" = "y" ] || [ "$response" = "Y" ] ; then
echo "-------------------------------------------------------------------------"
echo "Please wait....";sleep 1 
echo "$website" > /tmp/databasename.txt
#echo $website | sed "s/\./_/" | sed "s/\-/_/" | cut -c1-14  > /tmp/databasename.txt  
sed -i 's/\./_/g' /tmp/databasename.txt
sed -i 's/\-/_/g' /tmp/databasename.txt
random=`date |md5sum |cut -c '1-4'`
dataname=`cat /tmp/databasename.txt | cut -c1-11`_$random
username=`cat /tmp/databasename.txt | sed "s/\_//" | sed "s/\_//" | sed "s/\_//" | sed "s/\_//" | cut -c1-10`$random
password=`date |md5sum |cut -c '14-29'`
rm -rf /tmp/databasename.txt

#
cat > "/tmp/config.temp" <<END
CREATE DATABASE $dataname COLLATE utf8_general_ci;
END

mysql -u root -p$mariadbpass < /tmp/config.temp
rm -f /tmp/config.temp

#
cat > "/tmp/config.temp" <<END
CREATE USER '$username'@'localhost' IDENTIFIED BY '$password';
END

mysql -u root -p$mariadbpass < /tmp/config.temp
rm -f /tmp/config.temp

#
cat > "/tmp/config.temp" <<END
GRANT ALL PRIVILEGES ON $dataname . * TO '$username'@'localhost';
END

mysql -u root -p$mariadbpass < /tmp/config.temp
rm -f /tmp/config.temp

#
cat > "/tmp/config.temp" <<END
FLUSH PRIVILEGES;
END

mysql -u root -p$mariadbpass < /tmp/config.temp
rm -f /tmp/config.temp

echo "=========================================================================" >> /home/DBinfo.txt
echo "Database: $dataname - Created on: $(date +%d/%m/%Y) when add $website to VPS" >> /home/DBinfo.txt
echo "=========================================================================" >> /home/DBinfo.txt
echo "Data name: $dataname" >> /home/DBinfo.txt
echo "Username: $username" >> /home/DBinfo.txt
echo "password: $password" >> /home/DBinfo.txt
echo "" >> /home/DBinfo.txt

#
systemctl reload nginx

clear
echo "========================================================================="
echo "$website them thanh cong vao server"
echo "-------------------------------------------------------------------------"
echo "Vhost File: /etc/nginx/conf.d/$website.conf"
echo "-------------------------------------------------------------------------"
echo "Upload code vao /home/$website/public_html"
echo "-------------------------------------------------------------------------"
echo "Database duoc tao tu dong cho $website :"
echo "-------------------------------------------------------------------------"
echo "Ten Database: $dataname"
echo "User name: $username" 
echo "Mat khau: $password"
echo "-------------------------------------------------------------------------"
echo "Thong tin database da duoc luu vao: /home/DBinfo.txt"
fi

#
/etc/vpssim/menu/centos9/option/them-website-menu
