#!/bin/bash 
. /home/vpssim.conf

#
cd ~

# kiểm tra và cài đặt FTP trước khi tạo website -> để còn tạo tài khoản FTP cho domain
/etc/vpssim/menu/centos9/option/ftpserver-menu-before

#
/etc/vpssim/menu/centos9/option/list-website-tren-vps-before

#
echo "========================================================================="
echo "Su dung chuc nang nay de them website vao server"
echo "-------------------------------------------------------------------------"
echo -n "Nhap ten mien/ Enter your domain [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`

if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "Vui long nhap ten mien/ Please enter your domain!"
/etc/vpssim/menu/centos9/option/them-website-menu
exit
fi

kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,12}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website khong dung dinh dang duoc ho tro/ Domain format error!!"
echo "-------------------------------------------------------------------------"
echo "Vui long thu lai/ Please try again!"
/etc/vpssim/menu/centos9/option/them-website-menu
exit
fi

if [ -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Ten mien da ton tai/ Domain exist! "$website
/etc/vpssim/menu/centos9/option/them-website-menu
exit
fi

#
mkdir -p "/home/$website/public_html"
mkdir -p "/home/$website/logs"
chmod 777 "/home/$website/logs"

#
yes | cp /etc/vpssim/menu/centos9/tmp/index.php "/home/$website/public_html/"
yes | cp /etc/vpssim/menu/centos9/tmp/robots.txt "/home/$website/public_html/"

#
chown -R nginx:nginx "/home/$website/public_html/"
find "/home/$website/public_html/" -type d -exec chmod g+s {} \;

#
yes | cp /etc/vpssim/menu/centos9/tmp/domain_vhost.conf "/etc/nginx/conf.d/$website.conf"
# thay domain trong file vhost
cat > "/tmp/vpssimSetConfigFile" <<END
#!/bin/bash 
sed -i 's/\%website\%/$website/g' "/etc/nginx/conf.d/$website.conf"
END
chmod +x /tmp/vpssimSetConfigFile
sh /tmp/vpssimSetConfigFile
rm -f /tmp/vpssimSetConfigFile

#
systemctl reload nginx

#
if [ ! -d /etc/vpssim/errorpage_html ]; then
	if [ -d /opt/echbay_vpssim/script/vpssim/errorpage_html ]; then
		mkdir -p /etc/vpssim/errorpage_html ; chmod 755 /etc/vpssim/errorpage_html
		yes | cp -rf /opt/echbay_vpssim/script/vpssim/errorpage_html/. /etc/vpssim/errorpage_html/
	fi
fi

mkdir -p /home/$website/errorpage_html && cp -r /etc/vpssim/errorpage_html/*.html /home/$website/errorpage_html


# nếu là thêm wordpress website -> mặc định là sẽ thêm database
if [ "$1" = "wordpress" ] || [ "$1" = "woocommerce" ]; then
response="y"
else
# còn không sẽ hỏi người dùng có thêm website hay không
echo "-------------------------------------------------------------------------"
echo -n "Ban co muon VPSSIM tao Database moi cho $website ? [y/N] " 
read response
fi

#
if [ "$response" = "y" ] || [ "$response" = "Y" ] ; then
/etc/vpssim/menu/centos9/option/add-database $website
fi

# download code wordpress
if [ "$1" = "wordpress" ] || [ "$1" = "woocommerce" ]; then
echo "TEST code wordpress"
fi

# download code woocommerce
if [ "$1" = "woocommerce" ]; then
echo "TEST code woocommerce"
fi


# thêm tài khoản FTP
/etc/vpssim/menu/centos9/option/tao-ftp-user-cho-domain $website

#
/etc/vpssim/menu/centos9/option/them-website-menu
