#!/bin/bash 

#
echo "========================================================================="
echo "Tao website, tai wordpress san sang de su dung"
echo "Add website, download wordpress for custom install"

#
/etc/vpssim/menu/centos9/option/them-website "wordpress"
