#!/bin/bash
if [ ! -f /etc/cron.d/vpssim.code.cron ]; then
touch /etc/cron.d/vpssim.code.cron
fi

prompt="Vui long chon/ Please choose (0 - Backspace):"
options=( "Add Website" "Add Database" "Add Wordpress website" "Add Wordpress demo" "List Website in Server")
printf "=========================================================================\n"
printf "                VPSSIM - Quan Ly VPS/ Server by EchBay.com \n"
printf "=========================================================================\n"
printf "                          Them Website Vao Server\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) /etc/vpssim/menu/centos9/option/them-website;;
    2) /etc/vpssim/menu/centos9/option/add-database-before;;
    3) /etc/vpssim/menu/centos9/option/them-wordpress-website;;
    4) /etc/vpssim/menu/centos9/option/them-wordpress-demo;;
    5) /etc/vpssim/menu/centos9/option/list-website-tren-vps;;
    0) clear && vpssim;;
    *) echo "Vui long chon theo danh sach/ Please choose from the list"; continue;;

    esac

done
