#!/bin/bash
. /home/vpssim.conf

echo "========================================================================="
echo "Su dung chuc nang nay de xem thong tin tai khoan FTP cua website"
echo "-------------------------------------------------------------------------"
/etc/vpssim/menu/centos9/option/list-website-tren-vps-before
echo "-------------------------------------------------------------------------"
echo -n "Nhap ten website [ENTER]: " 
read website

#
/etc/vpssim/menu/centos9/option/ftpserver-menu-validate $website

#
if [ "$(pure-pw list | grep "/home/$website/")" == "" ]; then
clear
echo "========================================================================="
echo "Website $website chua tao tai khoan FTP !"
/etc/vpssim/menu/centos9/option/ftpserver-menu
fi

echo "========================================================================="
echo "Tim thay $website tren he thong"
echo "-------------------------------------------------------------------------"
echo "$website da duoc tao tai khoan FTP"
echo "-------------------------------------------------------------------------"
echo "VPSSIM dang lay thong tin"
echo "-------------------------------------------------------------------------"
echo "Please wait...."
sleep 5
clear
echo "========================================================================="
echo "Thong tin login tai khoan FTP cua $website:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip"
echo "-------------------------------------------------------------------------"
echo "Username: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}') | Password: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $10}')"

/etc/vpssim/menu/centos9/option/ftpserver-menu
