#!/bin/bash
. /home/vpssim.conf

#
/etc/vpssim/menu/centos9/inc/list-website-tren-vps-before

#
echo "========================================================================="
echo "Su dung chuc nang nay de xem thong tin tai khoan FTP cua website"
echo "-------------------------------------------------------------------------"
echo -n "Chon ten website/ Please choose website [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`

#
if [ "$website" = "" ]; then
clear
/etc/vpssim/menu/centos9/option/ftpserver-menu
exit
fi

# xem số này có chứa thông tin tên miền tương ứng không
if [ -f "/tmp/domain_number$website.txt" ]; then
# có thì lấy tên miền trong file
website=`cat /tmp/domain_number$website.txt`
echo "Ten mien/ Domain: "$website
else
clear
echo "========================================================================="
echo "Vui long chon lai/ Please choose again!"
echo "-------------------------------------------------------------------------"
/etc/vpssim/menu/centos9/option/view-userftp-password
exit
fi

#
/etc/vpssim/menu/centos9/inc/ftpserver-menu-validate $website

#
if [ "$(pure-pw list | grep "/home/$website/")" == "" ]; then
clear
echo "========================================================================="
echo "Website $website chua tao tai khoan FTP !"
/etc/vpssim/menu/centos9/option/ftpserver-menu
exit
fi

echo "========================================================================="
echo "Tim thay $website tren he thong"
echo "-------------------------------------------------------------------------"
echo "$website da duoc tao tai khoan FTP"
echo "-------------------------------------------------------------------------"
echo "VPSSIM dang lay thong tin"
echo "-------------------------------------------------------------------------"
echo "Please wait...."

clear
echo "========================================================================="
echo "Thong tin login tai khoan FTP cua $website:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip"
echo "-------------------------------------------------------------------------"
echo "Username: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}') | Password: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $10}')"

#
/etc/vpssim/menu/centos9/option/ftpserver-menu
exit
