#!/bin/bash
. /home/vpssim.conf


if [ ! -d /etc/vpssim/.tmp ]; then
mkdir -p /etc/vpssim/.tmp
fi


#checkketnoi=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "https://vpssim.vn/script/vpssim/vpssim.newversion" )
checkketnoi=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "https://raw.githubusercontent.com/itvn9online/vpssim-free/master/version" )
#echo $checkketnoi
if [[ "$checkketnoi" == "000" ]]; then
clear
echo "========================================================================="
echo "Co loi xay ra trong qua trinh update"
echo "-------------------------------------------------------------------------"
echo "Ban vui long thu lai !"
vpssim
exit
fi


# update glibc
wget --no-check-certificate -q https://raw.githubusercontent.com/itvn9online/vpssim-free/master/script/vpssim/vpssim-update-glibc -O /etc/vpssim/.tmp/vpssim-update-glibc
chmod +x /etc/vpssim/.tmp/vpssim-update-glibc
bash /etc/vpssim/.tmp/vpssim-update-glibc


## Bat dau thuc hien update VPSSIM
#wget -q https://vpssim.vn/script/vpssim/vpssim-update-run -O /etc/vpssim/.tmp/vpssim-update-run && chmod +x /etc/vpssim/.tmp/vpssim-update-run
#wget --no-check-certificate -q https://raw.githubusercontent.com/itvn9online/vpssim-free/master/script/vpssim/vpssim-update-run -O /etc/vpssim/.tmp/vpssim-update-run
#chmod +x /etc/vpssim/.tmp/vpssim-update-run
#bash /etc/vpssim/.tmp/vpssim-update-run


