#!/bin/bash
. /home/vpssim.conf

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then

XXX=x86_64
YYY=x86_64

if [ ! -d /etc/vpssim/.tmp ]; then
mkdir -p /etc/vpssim/.tmp
fi

cd
rm -rf /etc/vpssim/.tmp/asnhzad
ldd --version | grep "2.17" > /etc/vpssim/.tmp/asnhzad

if [ "$(wc -c < /etc/vpssim/.tmp/asnhzad)" -lt "1" ]; then
ldd --version
sudo yum clean all
sudo yum -y update glibc

echo $XXX
echo $YYY

ketnoi=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-x86_64/glibc-2.17-55.fc20/glibc-2.17-55.el6.x86_64.rpm")
#echo $ketnoi
if [[ "$ketnoi" != "000" ]]; then
wget http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-$YYY/glibc-2.17-55.fc20/glibc-2.17-55.el6.$XXX.rpm
wget http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-$YYY/glibc-2.17-55.fc20/glibc-common-2.17-55.el6.$XXX.rpm
wget http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-$YYY/glibc-2.17-55.fc20/glibc-devel-2.17-55.el6.$XXX.rpm
wget http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-$YYY/glibc-2.17-55.fc20/glibc-headers-2.17-55.el6.$XXX.rpm
else
#wget --no-check-certificate https://vpssim.com/script/vpssim/Softwear/glibc_2.17/glibc-2.17-55.el6.$XXX.rpm
wget --no-check-certificate https://github.com/itvn9online/echbay-vpssim-software/raw/master/glibc_2.17/glibc-2.17-55.el6.$XXX.rpm
#wget --no-check-certificate https://vpssim.com/script/vpssim/Softwear/glibc_2.17/glibc-common-2.17-55.el6.$XXX.rpm
wget --no-check-certificate https://github.com/itvn9online/echbay-vpssim-software/raw/master/glibc_2.17/glibc-common-2.17-55.el6.$XXX.rpm
#wget --no-check-certificate https://vpssim.com/script/vpssim/Softwear/glibc_2.17/glibc-devel-2.17-55.el6.$XXX.rpm
wget --no-check-certificate https://github.com/itvn9online/echbay-vpssim-software/raw/master/glibc_2.17/glibc-devel-2.17-55.el6.$XXX.rpm
#wget --no-check-certificate https://vpssim.com/script/vpssim/Softwear/glibc_2.17/glibc-headers-2.17-55.el6.$XXX.rpm
wget --no-check-certificate https://github.com/itvn9online/echbay-vpssim-software/raw/master/glibc_2.17/glibc-headers-2.17-55.el6.$XXX.rpm
fi

sudo rpm -Uvh glibc-2.17-55.el6.$XXX.rpm \
glibc-common-2.17-55.el6.$XXX.rpm \
glibc-devel-2.17-55.el6.$XXX.rpm \
glibc-headers-2.17-55.el6.$XXX.rpm #--force --nodeps

if [ "$(ldd --version | grep "2.17" | wc -c)" -lt "1" ]; then
sudo rpm -Uvh glibc-2.17-55.el6.$XXX.rpm \
glibc-common-2.17-55.el6.$XXX.rpm \
glibc-devel-2.17-55.el6.$XXX.rpm \
glibc-headers-2.17-55.el6.$XXX.rpm --force --nodeps
fi

sleep 5

# Note: If you see that it is not showing the above new version, probably your yum cache should be updated. In that case, do the following and then try the yum update again.
sudo yum clean all
sudo yum -y update glibc

rm -rf /root/glibc*

rm -rf /etc/vpssim/.tmp/asnhzad
ldd --version | grep "2.17" > /etc/vpssim/.tmp/asnhzad
if [ "$(wc -c < /etc/vpssim/.tmp/asnhzad)" -lt "1" ]; then
clear
echo "========================================================================="
echo "Qua trinh cap nhat glibc that bai"
echo "========================================================================="
fi

ldd --version

fi

#rm -rf /etc/vpssim/.tmp/asnhzad
#######
######################

fi
