#!/bin/sh
#curTime=$(date +%d)
#checktruenumber='^[0-9]+$'
if [ $(id -u) != "0" ]; then
    printf "Co loi ! VPSSIM chi chay tren user root !\n"
    exit
fi

#  sử dụng menu theo OS version
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then
/etc/vpssim/menu/centos7/main-menu
else
/etc/vpssim/menu/centos9/main-menu
fi