#!/bin/bash

#
cd ~
if [ ! -f /tmp/vpssim.conf ]; then
cd /opt/echbay_vpssim
chmod +x install-before
bash install-before
cd ~
fi
. /tmp/vpssim.conf

#
if [ "$vpssimemail" = "" ] || [ "$svport" = "" ]; then
clear
echo "ERROR include custom config!"
exit
fi

#
#phpmacdinh="7.4"
#numPHPmacdinh="74"
echo "=========================================================================="
#echo "Mac dinh server se duoc cai dat PHP "$phpmacdinh". Neu muon su dung phien ban PHP "
#echo "--------------------------------------------------------------------------"
#echo "khac, sau khi cai dat server xong dung chuc nang [ Change PHP Version ] "
#echo "--------------------------------------------------------------------------"
#echo "trong [ Update System ] cua ECHBAY-VPSSIM."
#echo "--------------------------------------------------------------------------"
echo "VPSSIM ho tro: PHP 8++"

free -m
df -h

echo "=========================================================================="
echo "Thong Tin Server:  "
echo "--------------------------------------------------------------------------"
#echo "Server Type: $(virt-what | awk 'NR==1 {print $NF}')"
echo "CPU Type: $cpuname"
echo "CPU Core: $cpucores"
echo "CPU Speed: $cpufreq MHz"
echo "Memory: $svram MB"
#echo "Disk: $svhdd"
echo "IP: $svip"
echo "=========================================================================="



#Download Nginx, VPSSIM & phpMyadmin Version
cd /tmp
#rm -rf 00-all-nginx-version.txt
rm -rf vpssim.newversion
rm -rf 00-all-phpmyadmin-version.txt

#
yes | cp -rf /opt/echbay_vpssim/script/vpssim/vpssim.newversion vpssim.newversion
yes | cp -rf /opt/echbay_vpssim/script/vpssim/00-all-phpmyadmin-version.txt 00-all-phpmyadmin-version.txt

#
cd ~


#
phpmyadmin_version=`cat /tmp/00-all-phpmyadmin-version.txt | awk 'NR==2 {print $1}' | sed 's/|//' | sed 's/|//'`

# Secure your MariaDB installation
passrootmysql=`date |md5sum |cut -c '1-16'`
echo "$passrootmysql" > /tmp/vpssim-mysqlrootpass

#
vpssim_version=`cat /tmp/vpssim.newversion`

#
clear

echo "=========================================================================="
echo "OS Version: "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))
echo "--------------------------------------------------------------------------"
echo "ECHBAY-VPSSIM Se Cai Dat Server Theo Thong Tin:"
echo "Your VPS will been install with config:"
echo "=========================================================================="
echo "eMail Quan Ly (admin email): $vpssimemail"
echo "--------------------------------------------------------------------------"
echo "phpMyAdmin Port: $svport"
echo "--------------------------------------------------------------------------"
echo "phpMyAdmin Version: $phpmyadmin_version"
echo "--------------------------------------------------------------------------"
echo "MariaDB Version: default by server"
echo "--------------------------------------------------------------------------"
echo "Mat khau root MySQL (MySQL root password): $passrootmysql"
echo "--------------------------------------------------------------------------"
echo "Nginx Version: default by server"
#echo "Nginx Version: Mainline version"
echo "--------------------------------------------------------------------------"
echo "PHP Version: 8++"
echo "--------------------------------------------------------------------------"
echo "ECHBAY-VPSSIM Version: $vpssim_version"
echo "=========================================================================="

prompt="Nhap lua chon cua ban (Please select): "
options=( "Toi dong y/ I agree" "Khong dong y / Disagree")
PS3="$prompt"
select opt in "${options[@]}"; do 
    case "$REPLY" in
    1) xacnhanthongtin="dongy"; break;;
    2) xacnhanthongtin="khongdongy"; break;;
    *) echo "Vui long chon theo danh sach/ Please choose from the list"; continue;;
    esac  
done

if [ "$xacnhanthongtin" = "dongy" ]; then
echo "--------------------------------------------------------------------------"
echo "Chuan Bi Cai Dat ECHBAY-VPSSIM ..."
#sleep 2
else 
clear
rm -rf /root/install && bash /root/vpssim-setup
exit
fi


#
sudo yum -y install zip unrar rsync psmisc


# current os version
current_os_version=$(rpm --eval '%{centos_ver}')

# tạo config để các script khi include còn có thông tin mà sử dụng
rm -f /home/vpssim.conf
cat > "/home/vpssim.conf" <<END
mainsite="vpssim.demo"
priport="$svport"
serverip="$svip"
emailmanage="$vpssimemail"
mariadbpass="$passrootmysql"
phpmyadmin_version="$phpmyadmin_version"
current_os_version="$current_os_version"
END
chmod +x /home/vpssim.conf


#
yum -y update
yum -y upgrade


# install
# https://duypt.dev/huong-dan-cai-dat-lemp-tren-centos-stream-9
# cài mysql trước -> để nếu có phần bắt nhập pass thì còn thấy sớm
/etc/vpssim/menu/centos9/install/mariadb
# xong mới cài các phần mềm tiếp theo
/etc/vpssim/menu/centos9/install/before_install
/etc/vpssim/menu/centos9/install/nginx
/etc/vpssim/menu/centos9/install/php
/etc/vpssim/menu/centos9/install/phpmyadmin


# another service
cd ~
sudo yum -y install sendmail sendmail-cf m4
systemctl start sendmail.service
systemctl enable sendmail.service

#
sudo yum -y install exim syslog-ng cronie cronie-anacron


#
clear
echo "=========================================================================="
echo "Cai Dat Hoan Tat, Bat Dau Qua Trinh Cau Hinh...... "
echo "=========================================================================="
#sleep 3

#
mkdir -p /home/vpssim.demo/public_html
cd /home/vpssim.demo/public_html

#
yes | cp -rf /opt/echbay_vpssim/script/vpssim/html/install/vietnam/index.html index.html
cd ~

# tao thu muc log va cac file log de phong truong hop cac ung dung khong the tu tao
mkdir -p /home/vpssim.demo/logs
chmod 777 /home/vpssim.demo/logs
touch /home/vpssim.demo/logs/mysql-slow.log
touch /home/vpssim.demo/logs/mysql.log
touch /home/vpssim.demo/logs/php-fpm-error.log
touch /home/vpssim.demo/logs/php-fpm-slow.log
touch /home/vpssim.demo/logs/php-fpm.log
chmod 777 /home/vpssim.demo/logs/*

mkdir -p /var/log/nginx
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/php/session


#
cd ~


#
#rm -rf /etc/nginx/conf.d
mkdir -p /etc/nginx/conf.d
yes | cp -rf /opt/echbay_vpssim/script/vpssim/centos9/conf/vpssim.demo.txt /etc/nginx/conf.d/vpssim.demo.conf
# config
cat > "/tmp/vpssimSetConfigFile" <<END
#!/bin/bash 
sed -i 's/tmp_listen_svport/$svport/g' /etc/nginx/conf.d/vpssim.demo.conf
sed -i '/ddos2.conf/d' /etc/nginx/conf.d/vpssim.demo.conf
sed -i '/auth_basic_user_file/d' /etc/nginx/conf.d/vpssim.demo.conf
sed -i '/auth_basic/d' /etc/nginx/conf.d/vpssim.demo.conf
END
chmod +x /tmp/vpssimSetConfigFile
sh /tmp/vpssimSetConfigFile
rm -rf /tmp/vpssimSetConfigFile


# ghi đè file nginx.conf mặc định
yes | cp -rf /opt/echbay_vpssim/script/vpssim/centos9/conf/nginx.txt /etc/nginx/nginx.conf


#
#rm -rf /etc/sysctl.conf
#yes | cp -rf /opt/echbay_vpssim/script/vpssim/conf-webserver/sysctl.txt /etc/sysctl.conf


#
#rm -rf /etc/php-fpm.conf
#yes | cp -rf /opt/echbay_vpssim/script/vpssim/conf-webserver/php-fpm.txt /etc/php-fpm.conf


#
mkdir -p /etc/vpssim

#
#echo "" > /etc/vpssim/pwprotect.default

cat > "/etc/vpssim/vpssim.version" <<END
${vpssim_version}
END

cat > "/etc/vpssim/phpmyadmin.version" <<END
${phpmyadmin_version}
END


#
if [ ! "$(grep LANG=en_US.utf-8 /etc/environment)" == "LANG=en_US.utf-8" ]; then
cat > "/etc/environment" <<END
LANG=en_US.utf-8
LC_ALL=en_US.utf-8
END
fi


#
#rm -f /var/lib/mysql/ib_logfile0
#rm -f /var/lib/mysql/ib_logfile1
#rm -f /var/lib/mysql/ibdata1


#
/etc/vpssim/menu/centos9/install/after_install



#
systemctl mask firewalld
systemctl stop firewalld
sudo yum -y install iptables*

#
if [ -f /etc/sysconfig/iptables ]; then
systemctl enable iptables 
systemctl enable ip6tables
systemctl start iptables
systemctl start ip6tables
systemctl start iptables.service

FIREWALLLIST="21 22 25 80 443 465 587 $svport 11211"
#echo $FIREWALLLIST
for PORT in ${FIREWALLLIST}; do
	if [ ! "$(iptables -L -n | grep :$PORT | awk 'NR==1 {print $1}')" == "ACCEPT" ]; then
		iptables -I INPUT -p tcp --dport ${PORT} -j ACCEPT
		iptables -I INPUT -p udp --dport ${PORT} -j ACCEPT
	else
		echo $PORT
	fi
done

# add ca ssh port hien tai neu no khong phai port 22
current_ssh_port=${SSH_CLIENT##* }
echo "current_ssh_port: "$current_ssh_port
if [ ! "$current_ssh_port" = "22" ]; then
iptables -I INPUT -p tcp --dport $current_ssh_port -j ACCEPT
fi

service iptables save
fi


#
sudo yum -y install certbot python3-certbot-nginx


#
clear
#echo "=========================================================================="
#echo "Setup CSF Firewall ... "
#echo "=========================================================================="
#sleep 3
#/etc/vpssim/menu/cai-csf-firewall-cai-dat-CSF-FIREWALL
#systemctl start memcached.service
#systemctl enable memcached.service 
rm -rf /root/install* && rm -rf /tmp/install*
rm -rf /root/vpssim-setup

#
cat > "/home/VPSSIM-manage-info.txt" <<END
=========================================================================
                           VPS MANAGE INFOMATION                         
=========================================================================

Calling ECHBAY-VPSSIM: vpssim

phpMyAdmin: http://$svip:$svport
MySQL root password: $passrootmysql

Zend Opcache: http://$svip:$svport/ocp.php
Memcache: http://$svip:$svport/memcache.php
Server Status: http://$svip/status.php

LUU Y: 
De VPS co hieu suat tot nhat - Hay bat: Zend Opcache, Memcached, 
va su dung cac Plugin cache(wp super cache....) cho website. 

Neu VPS dang bat Zend Opcache, khi edit file PHP, do cac file php duoc cache vao RAM  
nen ban can clear Zend Opcache de thay doi duoc cap nhat. 

Chuc ban se thanh cong cung ECHBAY-VPSSIM.
=========================================================================
END



# increase SSH login speed
if [ -f /etc/ssh/sshd_config ]; then 
sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
sed -i 's/#UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config
fi



#
clear
echo "=========================================================================="
echo "VPSSIM has completed the server installation."
echo "=========================================================================="
cat /home/VPSSIM-manage-info.txt
echo "=========================================================================="
echo "The server will automatically restart after 3 seconds...."
sleep 3
reboot
exit
