#!/bin/bash

#
checktruenumber='^[0-9]+$'

kiemtraemail3="^(([-a-zA-Z0-9\!#\$%\&\'*+/=?^_\`{\|}~])+\.)*[-a-zA-Z0-9\!#\$%\&\'*+/=?^_\`{\|}~]+@\w((-|\w)*\w)*\.(\w((-|\w)*\w)*\.)*\w{2,24}$";
svip=$(wget http://ipecho.net/plain -O - -q ; echo)
#phpmacdinh="7.4"
#numPHPmacdinh="74"
echo "=========================================================================="
#echo "Mac dinh server se duoc cai dat PHP "$phpmacdinh". Neu muon su dung phien ban PHP "
#echo "--------------------------------------------------------------------------"
#echo "khac, sau khi cai dat server xong dung chuc nang [ Change PHP Version ] "
#echo "--------------------------------------------------------------------------"
#echo "trong [ Update System ] cua ECHBAY-VPSSIM."
#echo "--------------------------------------------------------------------------"
echo "VPSSIM ho tro: PHP 8++"
cpuname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
cpucores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
cpufreq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
svram=$( free -m | awk 'NR==2 {print $2}' )
svhdd=$( df -h | awk 'NR==2 {print $2}' )
svswap=$( free -m | awk 'NR==4 {print $2}' )
free -m
df -h
echo "=========================================================================="
echo "Thong Tin Server:  "
echo "--------------------------------------------------------------------------"
#echo "Server Type: $(virt-what | awk 'NR==1 {print $NF}')"
echo "CPU Type: $cpuname"
echo "CPU Core: $cpucores"
echo "CPU Speed: $cpufreq MHz"
echo "Memory: $svram MB"
#echo "Disk: $svhdd"
echo "IP: $svip"
echo "--------------------------------------------------------------------------"
echo "Dien Thong Tin Cai Dat: "
echo "=========================================================================="
echo -n "Nhap Phpmyadmin Port [ENTER]: " 
read svport
if [ "$svport" = "80" ] || [ "$svport" = "443" ] || [ "$svport" = "22" ] || [ "$svport" = "3306" ] || [ "$svport" = "25" ] || [ "$svport" = "465" ] || [ "$svport" = "587" ] || [ "$svport" = "21" ]; then
	svport="1241"
echo "Phpmyadmin khong the trung voi port cua dich vu khac !"
echo "ECHBAY-VPSSIM se dat phpmyadmin port la "$svport
fi
if [ "$svport" = "" ] ; then
clear
echo "=========================================================================="
echo "$svport khong duoc de trong."
echo "--------------------------------------------------------------------------"
echo "Ban hay kiem tra lai !" 
bash /root/vpssim-setup
exit
fi
if ! [[ $svport -ge 100 && $svport -le 65535  ]] ; then  
clear
echo "=========================================================================="
echo "$svport khong hop le!"
echo "--------------------------------------------------------------------------"
echo "Port hop le la so tu nhien nam trong khoang (100 - 65535)."
echo "--------------------------------------------------------------------------"
echo "Ban hay kiem tra lai !" 
echo "-------------------------------------------------------------------------"
read -p "Nhan [Enter] de tiep tuc ..."
clear
bash /root/vpssim-setup
exit
fi

echo "--------------------------------------------------------------------------"
echo -n "Nhap dia chi email quan ly [ENTER]: " 
read vpssimemail
if [ "$vpssimemail" = "" ]; then
clear
echo "=========================================================================="
echo "Ban nhap sai, vui long nhap lai!"
echo "-------------------------------------------------------------------------"
read -p "Nhan [Enter] de tiep tuc ..."
clear
bash /root/vpssim-setup
exit
fi

if [[ ! "$vpssimemail" =~ $kiemtraemail3 ]]; then
clear
echo "=========================================================================="
echo "$vpssimemail co le khong dung dinh dang email!"
echo "--------------------------------------------------------------------------"
echo "Ban vui long thu lai  !"
echo "-------------------------------------------------------------------------"
read -p "Nhan [Enter] de tiep tuc ..."
clear
bash /root/vpssim-setup
exit
fi


#
phpmyadmin_version=`cat /opt/echbay_vpssim/script/vpssim/00-all-phpmyadmin-version.txt | awk 'NR==2 {print $1}' | sed 's/|//' | sed 's/|//'`
# Secure your MariaDB installation
passrootmysql=`date |md5sum |cut -c '1-16'`
#echo "$passrootmysql" > /tmp/passrootmysql


#
clear

echo "=========================================================================="
echo "OS Version: "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))
echo "--------------------------------------------------------------------------"
echo "ECHBAY-VPSSIM Se Cai Dat Server Theo Thong Tin:"
echo "Your VPS will been install with config:"
echo "=========================================================================="
echo "eMail Quan Ly (admin email): $vpssimemail"
echo "--------------------------------------------------------------------------"
echo "phpMyAdmin Port: $svport"
echo "--------------------------------------------------------------------------"
echo "phpMyAdmin Version: $phpmyadmin_version"
echo "--------------------------------------------------------------------------"
echo "MariaDB Version: default by server"
echo "--------------------------------------------------------------------------"
echo "Mat khau root MySQL (MySQL root password): $passrootmysql"
echo "--------------------------------------------------------------------------"
echo "Nginx Version: default by server"
#echo "Nginx Version: Mainline version"
echo "--------------------------------------------------------------------------"
echo "PHP Version: 8++"
echo "--------------------------------------------------------------------------"
#echo "ECHBAY-VPSSIM Version: $vpssim_version"
echo "=========================================================================="
prompt="Nhap lua chon cua ban (Please select): "
options=( "Dong Y (agree)" "Khong Dong Y (disagree)")
PS3="$prompt"
select opt in "${options[@]}"; do 
    case "$REPLY" in
    1) xacnhanthongtin="dongy"; break;;
    2) xacnhanthongtin="khongdongy"; break;;
    *) echo "Ban nhap sai ! Ban vui long chon so trong danh sach"; continue;;
    esac  
done

if [ "$xacnhanthongtin" = "dongy" ]; then
echo "--------------------------------------------------------------------------"
echo "Chuan Bi Cai Dat ECHBAY-VPSSIM ..."
#sleep 2
else 
clear
rm -rf /root/install && bash /root/vpssim-setup
exit
fi




#
yum -y update
yum -y upgrade


# https://duypt.dev/huong-dan-cai-dat-lemp-tren-centos-stream-9
echo "=========================================================================="
echo "Install Nginx"
#sleep 2
yum install nginx -y
#nginx -v
#nginx -V
# Bắt đầu khởi chạy web server
systemctl start nginx

# Tự động khởi chạy web server mỗi khi chúng ta reboot Cloud Instance
systemctl enable nginx

# Kiểm tra trạng thái web server
#systemctl status nginx

# Cho phép các kết nối http
firewall-cmd --permanent --zone=public --add-service=http 

# Cho phép các kết nối https
firewall-cmd --permanent --zone=public --add-service=https

# Khởi chạy lại firewall service
firewall-cmd --reload

#
chown nginx:nginx /usr/share/nginx/html -R


#
echo "=========================================================================="
echo "Install MariaDB..."
#sleep 2
yum install mariadb-server mariadb -y

#
systemctl start mariadb
systemctl enable mariadb
#systemctl status mariadb

#
#sudo mysqladmin version

#mysql_secure_installation

#
DATABASE_PASS=$passrootmysql

#
mysqladmin -u root password "$DATABASE_PASS"
# Make sure that NOBODY can access the server without a password
#mysql -u root -p"$DATABASE_PASS" -e "UPDATE mysql.user SET Password=PASSWORD('$DATABASE_PASS') WHERE User='root'"
#mysql -u root -p"$DATABASE_PASS" -e "SET PASSWORD FOR 'root'@localhost = PASSWORD('$DATABASE_PASS')"
# Kill the anonymous users
mysql -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
mysql -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.user WHERE User=''"
# Kill off the demo database
mysql -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
# Make our changes take effect
mysql -u root -p"$DATABASE_PASS" -e "FLUSH PRIVILEGES"



#
#sudo dnf module enable php:remi-8.2
echo "=========================================================================="
echo "Install php module..."
#sleep 2
yum install php php-fpm php-mysqlnd php-common php-json php-opcache php-ldap php-gd php-bcmath php-ctype php-fileinfo php-xml php-curl php-mbstring php-zip -y

#Configure sessions directory permissions
mkdir -p /var/lib/php/session
chown -R nginx:nginx /var/lib/php
chmod 777 /var/lib/php/session
#chmod +t /var/lib/php/session


#
systemctl start php-fpm
systemctl enable php-fpm
#systemctl status php-fpm

#
#nano /etc/php-fpm.d/www.conf
sed -i 's/user = apache/user = nginx/g' /etc/php-fpm.d/www.conf
sed -i 's/group = apache/group = nginx/g' /etc/php-fpm.d/www.conf

#Tune PHP-FPM pool settings
sed -i "s/;listen\.mode =.*/listen.mode = 0666/" /etc/php-fpm.d/www.conf
sed -i "s/;request_terminate_timeout =.*/request_terminate_timeout = 60/" /etc/php-fpm.d/www.conf
sed -i "s/pm\.max_children =.*/pm.max_children = 70/" /etc/php-fpm.d/www.conf
sed -i "s/pm\.start_servers =.*/pm.start_servers = 20/" /etc/php-fpm.d/www.conf
sed -i "s/pm\.min_spare_servers =.*/pm.min_spare_servers = 20/" /etc/php-fpm.d/www.conf
sed -i "s/pm\.max_spare_servers =.*/pm.max_spare_servers = 35/" /etc/php-fpm.d/www.conf
sed -i "s/;pm\.max_requests =.*/pm.max_requests = 500/" /etc/php-fpm.d/www.conf

#Tweak PHP-FPM settings
sed -i "s/error_reporting = .*/error_reporting = E_ALL \& ~E_NOTICE \& ~E_STRICT \& ~E_DEPRECATED/" /etc/php.ini
sed -i "s/display_errors = .*/display_errors = On/" /etc/php.ini
sed -i "s/memory_limit = .*/memory_limit = 512M/" /etc/php.ini
sed -i "s/upload_max_filesize = .*/upload_max_filesize = 256M/" /etc/php.ini
sed -i "s/post_max_size = .*/post_max_size = 256M/" /etc/php.ini
sed -i "s/;date.timezone.*/date.timezone = UTC/" /etc/php.ini


#
rm -rf /etc/php.d/*opcache*
yes | cp -rf /opt/echbay_vpssim/script/vpssim/conf-webserver/opcache.ini /etc/php.d/opcache.ini

#
systemctl restart nginx php-fpm


#
echo "=========================================================================="
echo "Install phpMyAdmin..."
#sleep 2

#
cd ~

#
mkdir -p /home/vpssim.demo
mkdir -p /home/vpssim.demo/private_html
rm -rf /home/vpssim.demo/private_html/*
# tao thu muc cho phpmyadmin dung lam cache
mkdir -p /home/vpssim.demo/private_html/tmp
chmod 777 /home/vpssim.demo/private_html/tmp
cd /home/vpssim.demo/private_html/

#
wget --no-check-certificate https://files.phpmyadmin.net/phpMyAdmin/${phpmyadmin_version}/phpMyAdmin-${phpmyadmin_version}-all-languages.zip
unzip -q phpMyAdmin-*.zip
yes | cp -rf phpMyAdmin-*/* .
rm -rf phpMyAdmin-*
randomblow=`date |md5sum |cut -c '1-32'`;
sed -e "s|cfg\['blowfish_secret'\] = ''|cfg['blowfish_secret'] = '$randomblow'|" config.sample.inc.php > config.inc.php




#
cd ~
sudo yum -y install sendmail sendmail-cf m4
systemctl start sendmail.service
systemctl enable sendmail.service

#
sudo yum -y install exim syslog-ng cronie cronie-anacron


#
clear
echo "=========================================================================="
echo "Cai Dat Hoan Tat, Bat Dau Qua Trinh Cau Hinh...... "
echo "=========================================================================="
#sleep 3

#
mkdir -p /home/vpssim.demo/public_html
cd /home/vpssim.demo/public_html

#
yes | cp -rf /opt/echbay_vpssim/script/vpssim/html/install/vietnam/index.html index.html
cd ~

# tao thu muc log va cac file log de phong truong hop cac ung dung khong the tu tao
mkdir -p /home/vpssim.demo/logs
chmod 777 /home/vpssim.demo/logs
touch /home/vpssim.demo/logs/mysql-slow.log
touch /home/vpssim.demo/logs/mysql.log
touch /home/vpssim.demo/logs/php-fpm-error.log
touch /home/vpssim.demo/logs/php-fpm-slow.log
touch /home/vpssim.demo/logs/php-fpm.log
chmod 777 /home/vpssim.demo/logs/*

mkdir -p /var/log/nginx
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/php/session


#
cd ~
cd /etc/nginx/
mkdir -p /etc/nginx/conf ; chmod 755 /etc/nginx/conf
yes | cp -rf /opt/echbay_vpssim/script/vpssim/conf/. /etc/nginx/conf/
find /etc/nginx/conf -type f -exec chmod 644 {} \;
cd ~


#
#rm -rf /etc/nginx/conf.d
mkdir -p /etc/nginx/conf.d
yes | cp -rf /opt/echbay_vpssim/script/vpssim/centos9/conf/vpssim.demo.txt /etc/nginx/conf.d/vpssim.demo.conf
# config
cat > "/tmp/vpssimSetConfigFile" <<END
#!/bin/bash 
sed -i 's/tmp_listen_svport/$svport/g' /etc/nginx/conf.d/vpssim.demo.conf
sed -i '/ddos2.conf/d' /etc/nginx/conf.d/vpssim.demo.conf
sed -i '/auth_basic_user_file/d' /etc/nginx/conf.d/vpssim.demo.conf
sed -i '/auth_basic/d' /etc/nginx/conf.d/vpssim.demo.conf
END
chmod +x /tmp/vpssimSetConfigFile
sh /tmp/vpssimSetConfigFile
rm -f /tmp/vpssimSetConfigFile


# ghi đè file nginx.conf mặc định
yes | cp -rf /opt/echbay_vpssim/script/vpssim/centos9/conf/nginx.txt /etc/nginx/nginx.conf


#
#rm -rf /etc/sysctl.conf
#yes | cp -rf /opt/echbay_vpssim/script/vpssim/conf-webserver/sysctl.txt /etc/sysctl.conf


#
#rm -rf /etc/php-fpm.conf
#yes | cp -rf /opt/echbay_vpssim/script/vpssim/conf-webserver/php-fpm.txt /etc/php-fpm.conf


#
mkdir -p /etc/vpssim

#
#echo "" > /etc/vpssim/pwprotect.default

cat > "/etc/vpssim/vpssim.version" <<END
${vpssim_version}
END

cat > "/etc/vpssim/phpmyadmin.version" <<END
${phpmyadmin_version}
END


#
if [ ! "$(grep LANG=en_US.utf-8 /etc/environment)" == "LANG=en_US.utf-8" ]; then
cat > "/etc/environment" <<END
LANG=en_US.utf-8
LC_ALL=en_US.utf-8
END
fi

#
rm -f /home/vpssim.conf
cat > "/home/vpssim.conf" <<END
mainsite="vpssim.demo"
priport="$svport"
serverip="$svip"
emailmanage="$vpssimemail"
mariadbpass="$passrootmysql"
END


#
#rm -f /var/lib/mysql/ib_logfile0
#rm -f /var/lib/mysql/ib_logfile1
#rm -f /var/lib/mysql/ibdata1


#
rm -rf /etc/motd
yes | cp -rf /opt/echbay_vpssim/script/vpssim/motd /etc/motd


#
yes | cp -rf /opt/echbay_vpssim/script/vpssim/vpssim /bin/vpssim && chmod +x /bin/vpssim

#
cd /etc/vpssim/
mkdir -p /etc/vpssim/menu ; chmod 755 /etc/vpssim/menu
yes | cp -rf /opt/echbay_vpssim/script/vpssim/menu/. /etc/vpssim/menu/
cd ~


#
mkdir -p /home/vpssim.demo/errorpage_html ; chmod 755 /home/vpssim.demo/errorpage_html
yes | cp -rf /opt/echbay_vpssim/script/vpssim/errorpage_html/. /home/vpssim.demo/errorpage_html/
mkdir -p /etc/vpssim/errorpage_html ; chmod 755 /etc/vpssim/errorpage_html
yes | cp -rf /opt/echbay_vpssim/script/vpssim/errorpage_html/. /etc/vpssim/errorpage_html/



#
systemctl mask firewalld
systemctl stop firewalld
sudo yum -y install iptables*

#
if [ -f /etc/sysconfig/iptables ]; then
systemctl enable iptables 
systemctl enable ip6tables
systemctl start iptables
systemctl start ip6tables
systemctl start iptables.service

FIREWALLLIST="21 22 25 80 443 465 587 $svport 11211"
#echo $FIREWALLLIST
for PORT in ${FIREWALLLIST}; do
	if [ ! "$(iptables -L -n | grep :$PORT | awk 'NR==1 {print $1}')" == "ACCEPT" ]; then
		iptables -I INPUT -p tcp --dport ${PORT} -j ACCEPT
		iptables -I INPUT -p udp --dport ${PORT} -j ACCEPT
	else
		echo $PORT
	fi
done 

# add ca ssh port hien tai neu no khong phai port 22
current_ssh_port=${SSH_CLIENT##* }
echo "current_ssh_port: "$current_ssh_port
if [ ! "$current_ssh_port" = "22" ]; then
iptables -I INPUT -p tcp --dport $current_ssh_port -j ACCEPT
fi

service iptables save
fi


#
sudo yum -y install certbot


#
clear
#echo "=========================================================================="
#echo "Setup CSF Firewall ... "
#echo "=========================================================================="
#sleep 3
#/etc/vpssim/menu/cai-csf-firewall-cai-dat-CSF-FIREWALL
#systemctl start memcached.service
#systemctl enable memcached.service 
rm -rf /root/install*
rm -rf /root/vpssim-setup

#
cat >> "/home/VPSSIM-manage-info.txt" <<END
=========================================================================
                           VPS MANAGE INFOMATION                         
=========================================================================

phpMyAdmin: http://$svip:$svport

Quan Ly Zend Opcache: http://$svip:$svport/ocp.php

Quan Ly Memcache: http://$svip:$svport/memcache.php

Xem Server Status: http://$svip/status.php

Lenh truy cap ECHBAY-VPSSIM: vpssim

LUU Y: 

De VPS co hieu suat tot nhat - Hay bat: Zend Opcache, Memcached, 
va su dung cac Plugin cache(wp super cache....) cho website. 

Neu VPS dang bat Zend Opcache, khi edit file PHP, do cac file php duoc cache vao RAM  
nen ban can clear Zend Opcache de thay doi duoc cap nhat. 

Chuc ban se thanh cong cung ECHBAY-VPSSIM .
END



# increase SSH login speed
if [ -f /etc/ssh/sshd_config ]; then 
sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
sed -i 's/#UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config
fi


#
cat > "/tmp/finishedemail.sh" <<END
#!/bin/bash 
echo -e 'Subject: ECHBAY-VPSSIM - Chuc mung cai dat thanh cong $svip!

Chao ban!

Chuc mung ban da hoan thanh qua trinh cai dat va cau hinh server $svip bang ECHBAY-VPSSIM.
Sau day la thong tin quan ly server cua ban:

+ Lenh goi ECHBAY-VPSSIM: vpssim
+ Link phpMyAdmin: http://$svip:$svport
+ Quan Ly Zend Opcache: http://$svip:$svport/ocp.php
+ Quan Ly Memcached: http://$svip:$svport/memcache.php
+ Xem Server Status: http://$svip/status.php

Luu Y:

+ Sau khi cai dat xong, neu server chua tao SWAP (RAM ao), ban tao them SWAP bang chuc nang [ Quan Ly Swap ] (Bat buoc).
+ De dat mat khau bao mat phpMyAdmin, backup files, ...: dung chuc nang [ BAT/TAT Bao Ve phpMyAdmin ] trong [ Quan Ly phpMyAdmin ]
+ De cai dat File Manager: Dung chuc nang [ Cai Dat File Manager ] 
+ Sau khi them website vao server, cai dat FTP server va tao tai khoan FTP cho tung website tren server bang chuc nang [ Quan Ly FTP Server ].
  Mac dinh ban khong the dang nhap FTP vao server bang tai khoan root. Neu muon dang nhap, ban phai dung sFTP voi thong tin dang nhap:
  Host: sftp://$svip  - User: root - Password: Your_password - Port: 22 (hoac port SSH ban da thay)
+ Neu server Timezone khong trung voi gio cua ban, cai dat lai time zone cho Server bang chuc nang [ Cai Dat Server Timezone ] trong [ Tien Ich - Addons ]
+ Sau khi Upload code len server. Ban phai chay chuc nang [ Fix Loi Chmod, Chown ] trong [ Tien Ich - Addons ] de thiet lap phan quyen cho website. 
  Neu website su dung code wordpress, thiet lap phan quyen cho website bang chuc nang [ Fix loi Permission ] trong [ Wordpress Blog Tools ]
+ Tuy theo so luong website, dung luong code ma ban cau hinh lai Zend Opcache, Memcached, Redis Cache bang chuc nang [ Quan Ly Memcached ], [ Quan Ly Zend Opcache ] , [ Quan Ly Redis Cache ] cho phu hop.
+ De bao mat, moi khi co dang nhap SSH va Server, ECHBAY-VPSSIM se gui email thong bao toi dia chi email $vpssimemail .
  Thay email hoac tat chuc nang nay bang [ BAT/TAT Email Thong Bao Login ] trong [ Tien ich - Addons ].  
  
ECHBAY-VPSSIM by Dao Quoc Dai - https://echbay.com' | exim  $vpssimemail
END
chmod +x /tmp/finishedemail.sh
/tmp/finishedemail.sh
rm -f /tmp/finishedemail.sh


#
clear
echo "=========================================================================="
echo "VPSSIM has completed the server installation. "
echo "=========================================================================="
echo "Calling ECHBAY-VPSSIM: vpssim"
echo "--------------------------------------------------------------------------"
echo "Link phpMyAdmin: http://$svip:$svport"
echo "--------------------------------------------------------------------------"
echo "Manage Zend Opcache: http://$svip:$svport/ocp.php"
echo "--------------------------------------------------------------------------"
#echo "Quan Ly Memcached: http://$svip:$svport/memcache.php"
#echo "--------------------------------------------------------------------------"
echo "View Server Status: http://$svip/status.php"
echo "--------------------------------------------------------------------------"
echo "Change login information: ECHBAY-VPSSIM menu ==> User & Password Mac Dinh. "
echo "=========================================================================="
echo "Management information is stored at: /home/VPSSIM-manage-info.txt "
echo "--------------------------------------------------------------------------"
echo "and attach a note to use ECHBAY-VPSSIM to email: $vpssimemail"
echo "=========================================================================="
echo "The server will automatically restart after 3 seconds.... "
#sleep 3
reboot
exit
