#!/bin/bash
printf "=========================================================================\n"
prompt="Lua chon cua ban:"
options=("Tim File Va Folder Trong public_html Cua Domain" "Tim File Va Folder Trong Folder Home")
PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
    1) /etc/vpssim/menu/tienich/vpssim-xem-danh-sach-max-dung-luong-file-domain;;
    2) /etc/vpssim/menu/tienich/vpssim-danh-sach-max-dung-luong-file-folder-home;;
$(( ${#options[@]}+1 )) ) echo "";  clear && /etc/vpssim/menu/vpssim-tien-ich;;
     *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done


