#!/bin/sh

cd ~
mkdir -p /etc/nginx/conf
download_echbay_nginx_config(){
wget --no-check-certificate -q "https://echbay.com/server/conf/index.php?file=$1&download=1&rand=1" -O /etc/nginx/conf/$1.conf ; chmod 600 /etc/nginx/conf/$1.conf
}
#download_echbay_nginx_config "ddos1"
#download_echbay_nginx_config "ddos2"
#download_echbay_nginx_config "ssl"
download_echbay_nginx_config "all"
download_echbay_nginx_config "block"
download_echbay_nginx_config "staticfiles"
download_echbay_nginx_config "drop"
service nginx restart

#
mkdir -p /usr/local/directadmin/data/templates/custom
cd /usr/local/directadmin/data/templates/custom
wget --no-check-certificate -q "https://raw.githubusercontent.com/itvn9online/openlitespeed-autoinstall/main/config/directadmin/openlitespeed_vhost.conf.CUSTOM.3.txt" -O openlitespeed_vhost.conf.CUSTOM.3.pre ; chmod 644 openlitespeed_vhost.conf.CUSTOM.3.pre
cd ~
