#!/bin/sh

cd ~
mkdir -p /etc/nginx/conf

download_echbay_nginx_config(){
wget --no-check-certificate -q "https://echbay.com/server/conf/index.php?file=$1&download=1&rand=1" -O /etc/nginx/conf/$1.conf ; chmod 755 /etc/nginx/conf/$1.conf
}
#download_echbay_nginx_config "ddos1"
#download_echbay_nginx_config "ddos2"
#download_echbay_nginx_config "ssl"
download_echbay_nginx_config "all"
download_echbay_nginx_config "block"
download_echbay_nginx_config "staticfiles"
download_echbay_nginx_config "drop"

#
chown root:root /etc/nginx/conf
chown root:root /etc/nginx/conf/*
chmod 755 /etc/nginx/conf/*


#
download_echbay_custom_nginx_config(){
wget --no-check-certificate -q "https://raw.githubusercontent.com/itvn9online/vpssim-free/master/directadmin/data/templates/custom/$1.conf" -O $1.conf ; chmod 755 $1.conf
}

cd ~
mkdir -p /usr/local/directadmin/data/templates/custom

#
cd /usr/local/directadmin/data/templates/custom
download_echbay_custom_nginx_config "nginx_server"
download_echbay_custom_nginx_config "nginx_server_secure"
download_echbay_custom_nginx_config "nginx_server_secure_sub"
download_echbay_custom_nginx_config "nginx_server_sub"


# file custom cho tất cả domain
download_echbay_custom_n_config(){
wget --no-check-certificate -q "https://raw.githubusercontent.com/itvn9online/vpssim-free/master/directadmin/data/templates/custom/nginx_server.conf.CUSTOM.3.txt" -O $1.conf.CUSTOM.3.pre ; chmod 755 $1.conf.CUSTOM.3.pre
}
download_echbay_custom_n_config "nginx_server"
download_echbay_custom_n_config "nginx_server_secure"
download_echbay_custom_n_config "nginx_server_secure_sub"
download_echbay_custom_n_config "nginx_server_sub"

#
cd ~

#
chown diradmin:diradmin /usr/local/directadmin/data/templates/custom
chown diradmin:diradmin /usr/local/directadmin/data/templates/custom/*
chmod 755 /usr/local/directadmin/data/templates/custom/*

#
cd /usr/local/directadmin/custombuild
./build rewrite_confs

cd ~
if [ -f /usr/local/lsws/bin/lswsctrl ]; then
/usr/local/lsws/bin/lswsctrl restart
else
service nginx restart
fi
