#!/bin/bash

echo "=========================================================================="
echo "chomod 755 menu... "
echo "=========================================================================="

find /etc/vpssim/menu -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/checkddos -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/crontab -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/CSF-Fiwall -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/database-example -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/downloadlog -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/memcache -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/menucheck -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/nang-cap-mariaDB -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/nangcap-php -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/opcache -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/pagespeed -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/swap -type f -exec chmod 755 {} \;
#find /etc/vpssim/menu/tienich -type f -exec chmod 755 {} \;

#for d in /opt/echbay_vpssim/script/vpssim/menu/*
for d in /etc/vpssim/menu/*
do
	if [ -d $d ]; then
		echo $d
		find $d -type f -exec chmod 755 {} \;
	fi
done
