#!/bin/sh

echo "-------------------------------------------------------------------------"
echo "Ok ! please wait check reset code from git..."

cd ~
if [ -d /opt/echbay_vpssim ]; then
rm -rf /opt/echbay_vpssim/*
rm -rf /opt/echbay_vpssim
sleep 5
fi

/etc/vpssim/menu/git-clone
sleep 1

clear
echo "========================================================================="
echo "Done! Reset code from git..."
/etc/vpssim/menu/vpssim-update-upgrade-service-menu
