#!/bin/sh

sudo yum -y install git

# update code
if [ -d /opt/echbay_vpssim ]; then
cd ~ ; cd /opt/echbay_vpssim && git pull ; cd ~
#git commit -m "ECHBAY-VPSSIM commit"
#git pull origin master
#git pull origin
#git merge origin master
# or clone new
else
git clone https://github.com/itvn9online/vpssim-free /opt/echbay_vpssim
fi

cd ~

sleep 5

find /opt/echbay_vpssim/script/vpssim/menu -type f -exec chmod 755 {} \;
/opt/echbay_vpssim/script/vpssim/menu/git-clone-done

