#!/bin/sh


cd ~
if [ -d /opt/echbay_vpssim ]; then
rm -rf /opt/echbay_vpssim/*
rm -rf /opt/echbay_vpssim
#sleep 5
fi

#
echo "Install unzip..."
sudo yum -y install unzip


# ưu tiên download file zip cho nó nhanh
cd /tmp
wget --no-check-certificate https://github.com/itvn9online/vpssim-free/archive/refs/heads/master.zip -O vpssim-free.zip
unzip -q vpssim-free.zip
cd ~
if [ -d /tmp/vpssim-free-master ]; then
    mkdir -p /opt/echbay_vpssim ; chmod 755 /opt/echbay_vpssim
    yes | cp -rf /tmp/vpssim-free-master/. /opt/echbay_vpssim/
    rm -rf /tmp/vpssim-free*
else
    echo "Install git..."
    sudo yum -y install git

    # update code
    if [ -d /opt/echbay_vpssim ]; then
        cd ~ ; cd /opt/echbay_vpssim && git pull ; cd ~
        #git commit -m "ECHBAY-VPSSIM commit"
        #git pull origin master
        #git pull origin
        #git merge origin master
        # or clone new
    else
        git clone https://github.com/itvn9online/vpssim-free /opt/echbay_vpssim
    fi
fi

#
cd ~

#sleep 5

find /opt/echbay_vpssim/script/vpssim/menu -type f -exec chmod 755 {} \;
/opt/echbay_vpssim/script/vpssim/menu/git-clone-done

#
echo "update ECHBAY-VPSSIM menu"
mkdir -p /etc/vpssim/menu ; chmod 755 /etc/vpssim/menu
rm -rf /etc/vpssim/menu/*
yes | cp -rf /opt/echbay_vpssim/script/vpssim/menu/. /etc/vpssim/menu/

echo "Chmod 755 Menu"
/opt/echbay_vpssim/script/vpssim/menu/chmod-755-menu

#
echo "update ECHBAY-VPSSIM conf"
mkdir -p /etc/nginx/conf ; chmod 755 /etc/nginx/conf
yes | cp -rf /opt/echbay_vpssim/script/vpssim/conf/. /etc/nginx/conf/
find /etc/nginx/conf -type f -exec chmod 644 {} \;
