#!/bin/bash
. /home/vpssim.conf

# copy code tu file install sang
cd ~
wget --no-check-certificate -q https://raw.githubusercontent.com/itvn9online/vpssim-free/master/script/vpssim/menu/git-clone
chmod +x /root/git-clone
bash /root/git-clone

#
cd ~
cd /tmp
rm -rf 00-all-nginx-version.txt
yes | cp -rf /opt/echbay_vpssim/script/vpssim/00-all-nginx-version.txt 00-all-nginx-version.txt

nginx -V

. /opt/echbay_vpssim/script/vpssim/nginx-setup.conf
echo "========================================================================="
echo "NEW nginx version: "${Nginx_VERSION}
echo "========================================================================="

# test
exit

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then
/opt/echbay_vpssim/script/vpssim/menu/nginx-setup6
else
/opt/echbay_vpssim/script/vpssim/menu/nginx-setup7
fi

cd ~

check_spdy_http2 () {
if [ ! "$(grep spdy /etc/nginx/conf.d/*.conf)" == "" ]; then 
sed -i 's/spdy/http2/g' /etc/nginx/conf.d/*.conf
fi
}
check_spdy_http2

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
systemctl restart nginx.service
else
service nginx restart
fi

rm -rf /opt/echbay_vpssim/*
rm -rf /opt/echbay_vpssim
sleep 1

clear
echo "========================================================================="
echo "Cai dat Nginx phien ban $Nginx_VERSION thanh cong !"
/etc/vpssim/menu/vpssim-update-upgrade-service-menu

