#!/bin/bash
. /home/vpssim.conf

#
cd ~
echo "========================================================================="
echo "which openssl (/usr/bin/openssl): "$(which openssl)
echo "openssl version: "$(openssl version)
echo "========================================================================="

echo -n "Ban muon cap nhat lai OpenSSL ? [y/N] "
read selectServer
if [ "$selectServer" = "y" ]; then
echo "-------------------------------------------------------------------------"
echo "Ok ! please wait check OpenSSL new version ...."
sleep 1

# them lenh kiem tra neu co git roi thi thoi khong tai lai nua
okResetGit="y"
if [ -d /opt/echbay_vpssim ]; then
echo "========================================================================="
echo "========================================================================="
echo "========================================================================="
echo -n "Ban co muon cap nhat lai git code moi khong? [y/N] "
read resetGit
if [ "$resetGit" = "y" ]; then
okResetGit="y"
echo "Ok ok! Chuan bi cap nhat lai code tu github..."
sleep 3
else
okResetGit="n"
fi
fi

# copy code tu file install sang
if [ "$okResetGit" = "y" ]; then
cd ~
wget --no-check-certificate -q https://raw.githubusercontent.com/itvn9online/vpssim-free/master/script/vpssim/menu/git-clone
chmod +x /root/git-clone
bash /root/git-clone
fi

. /opt/echbay_vpssim/script/vpssim/nginx-setup.conf
echo "========================================================================="
echo "NEW openssl version: "${opensslversion}
echo "========================================================================="

# neu truoc do hoi nguoi dung ve viec cap nhat git, nguoi dung chon y roi thi o buoc nay dat y luon, do phai hoi lai
if [ "$okResetGit" = "y" ]; then
selectOpenSSL="y"
else
echo -n "Ban that su muon thay doi sang phien ban "${opensslversion}" ? [y/N] "
read selectOpenSSL
fi

if [ "$selectOpenSSL" = "y" ]; then
echo "Ok ! please wait update "${opensslversion}" ...."
sleep 1

#
/opt/echbay_vpssim/script/vpssim/menu/nang-cap-openssl-auto

#
openssl version

else
echo "Ban da huy thay doi phien ban "${opensslversion}
fi

else
echo "Ban da huy thay doi phien ban OpenSSL"
fi

#
/etc/vpssim/menu/vpssim-update-upgrade-service-menu

