#!/bin/bash
. /home/vpssim.conf

#
cd ~
if [ -d /opt/echbay_vpssim ]; then
	rm -rf /opt/echbay_vpssim/*
	rm -rf /opt/echbay_vpssim
	sleep 5
fi

sudo yum -y install git
git clone https://github.com/itvn9online/vpssim-free /opt/echbay_vpssim
sleep 5

find /opt/echbay_vpssim/script/vpssim/menu -type f -exec chmod 755 {} \;
/opt/echbay_vpssim/script/vpssim/menu/git-clone-done

#
cd ~
cd /tmp
rm -rf 00-all-nginx-version.txt
yes | cp -rf /opt/echbay_vpssim/script/vpssim/00-all-nginx-version.txt 00-all-nginx-version.txt

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then
/opt/echbay_vpssim/script/vpssim/menu/nginx-setup6
else
/opt/echbay_vpssim/script/vpssim/menu/nginx-setup7
fi

cd ~

check_spdy_http2 () {
if [ ! "$(grep spdy /etc/nginx/conf.d/*.conf)" == "" ]; then 
sed -i 's/spdy/http2/g' /etc/nginx/conf.d/*.conf
fi
}
check_spdy_http2

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
systemctl restart nginx.service
else
service nginx restart
fi

rm -rf /opt/echbay_vpssim/*
rm -rf /opt/echbay_vpssim
sleep 1

clear
echo "========================================================================="
echo "Cai dat Nginx phien ban $Nginx_VERSION thanh cong !"
/etc/vpssim/menu/vpssim-update-upgrade-service-menu

