#!/bin/bash

. /opt/echbay_vpssim/script/vpssim/nginx-setup.conf
echo $moduledir
echo $opensslversion
echo $zlibversion
echo $pcreVersionInstall
echo $Nginx_VERSION
#exit


/opt/echbay_vpssim/script/vpssim/menu/nginx-setup-download


cd
cd /usr/local/vpssim
#cai dat  nginx
wget -q http://nginx.org/download/nginx-${Nginx_VERSION}.tar.gz
tar -xzf nginx-${Nginx_VERSION}.tar.gz
rm -rf /usr/local/vpssim/nginx-${Nginx_VERSION}.tar.gz 
cd /usr/local/vpssim/nginx-${Nginx_VERSION}
#sed -i 's/"Server: nginx"/"Server: Nginx-VPSSIM"/g' /usr/local/vpssim/nginx-${Nginx_VERSION}/src/http/ngx_http_header_filter_module.c
#sed -i 's/"Server: "/"Server: Nginx-VPSSIM"/g' /usr/local/vpssim/nginx-${Nginx_VERSION}/src/http/ngx_http_header_filter_module.c
./configure --group=nginx --user=nginx \
--pid-path=/var/run/nginx.pid \
--prefix=/usr/share/nginx \
--sbin-path=/usr/sbin/nginx \
--with-http_v2_module \
--with-http_ssl_module \
--with-ipv6 \
--with-http_flv_module \
--with-http_mp4_module \
--with-http_random_index_module \
--with-http_secure_link_module \
--with-http_stub_status_module \
--with-http_sub_module \
--with-http_xslt_module \
--with-http_addition_module \
--with-http_dav_module \
--with-http_geoip_module \
--with-http_image_filter_module \
--with-http_perl_module \
--with-ld-opt="-Wl,-E" \
--with-mail \
--with-mail_ssl_module \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-file-aio \
--with-pcre=$moduledir/${pcreVersionInstall} \
--with-pcre-jit \
--with-google_perftools_module \
--with-debug \
--with-zlib=$moduledir/${zlibversion} \
--with-openssl=$moduledir/${opensslversion} \
--with-openssl-opt="enable-tlsext" \
--conf-path=/etc/nginx/nginx.conf \
--with-http_gzip_static_module \
--with-threads \
--with-stream \
--with-stream_ssl_module \
--with-http_realip_module \
--add-module=$moduledir/ngx_devel_kit-master \
--add-module=$moduledir/echo-nginx-module-master \
--add-module=$moduledir/memc-nginx-module-master \
--add-module=$moduledir/set-misc-nginx-module-master \
--add-module=$moduledir/srcache-nginx-module-master \
--add-module=$moduledir/ngx_http_concat \
--add-module=$moduledir/ngx_http_substitutions_filter_module-master \
--add-module=$moduledir/ngx_cache_purge-master \
--add-module=$moduledir/headers-more-nginx-module-master \
--add-module=$moduledir/redis2-nginx-module-master \
--add-module=$moduledir/ngx_http_redis-0.3.8 


make
make install
############################
# Download init & config file for nginx
rm -f /etc/init.d/nginx
download_initd_nginx () {
#wget --no-check-certificate -q https://hostingaz.vn/script/vpssim/nginx -O /etc/init.d/nginx && chmod +x /etc/init.d/nginx
yes | cp -rf /opt/echbay_vpssim/script/vpssim/nginx /etc/init.d/nginx && chmod +x /etc/init.d/nginx
}
download_initd_nginx
checkdownload_initd_nginx=`cat /etc/init.d/nginx`
if [ -z "$checkdownload_initd_nginx" ]; then
download_initd_nginx
fi
chmod +x /usr/sbin/nginx
rm -rf /etc/nginx/nginx.conf
mv /tmp/nginx.conf /etc/nginx/nginx.conf

echo "=========================================================================="
echo "Cai Dat Hoan Tat Nginx "
echo "=========================================================================="
#exit
sleep 5

# End Download init & config file for nginx
