#!/bin/bash

#
. /opt/echbay_vpssim/script/vpssim/nginx-setup.conf
echo "Install after 3s"
sleep 3

# https://www.linuxbabe.com/nginx/install-nginx-mainline-version-centos7
cat > "/etc/yum.repos.d/nginx.repo" <<END
[nginx.org]
name=nginx.org repo
baseurl=http://nginx.org/packages/centos/7/\$basearch/
gpgcheck=1
enabled=1
END

#
wget http://nginx.org/keys/nginx_signing.key
sudo rpm --import nginx_signing.key
yum -y update

#
#/opt/echbay_vpssim/script/vpssim/menu/nang-cap-openssl-before

# install nginx Mainline version
sudo yum -y install nginx
sudo systemctl start nginx
sudo systemctl status nginx
sudo systemctl enable nginx
nginx -V
nginx -v
sleep 6

#
cat > "/etc/vpssim/nginx.version" <<END
${Nginx_VERSION}
END
