#!/bin/bash

. /opt/echbay_vpssim/script/vpssim/nginx-setup.conf


echo "=========================================================================="
echo "Download Nginx Module ... "
echo "=========================================================================="

#
cd /usr/local/vpssim

# /usr/local/vpssim/echo-nginx-module
rm -rf echo-nginx-module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/echo-nginx-module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/echo-nginx-module.zip echo-nginx-module.zip
unzip -oq echo-nginx-module.zip
rm -rf echo-nginx-module.zip

# /usr/local/vpssim/ngx_http_substitutions_filter_module
rm -rf ngx_http_substitutions_filter_module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/ngx_http_substitutions_filter_module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/ngx_http_substitutions_filter_module.zip ngx_http_substitutions_filter_module.zip
unzip -oq ngx_http_substitutions_filter_module.zip
rm -rf ngx_http_substitutions_filter_module.zip

# /usr/local/vpssim/ngx_cache_purge-master
rm -rf ngx_cache_purge*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/ngx_cache_purge.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/ngx_cache_purge.zip ngx_cache_purge.zip
unzip -oq ngx_cache_purge.zip

rm -rf ngx_cache_purge.zip
# /usr/local/vpssim/headers-more-nginx-module
rm -rf headers-more-nginx-module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/headers-more-nginx-module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/headers-more-nginx-module.zip headers-more-nginx-module.zip
unzip -oq headers-more-nginx-module.zip
rm -rf headers-more-nginx-module.zip

# /usr/local/vpssim/openssl-1.0.2h
rm -rf ${opensslversion}
#wget -q --no-check-certificate https://vpssim.com/script/vpssim/module-nginx/${opensslversion}.tar.gz
if [ -f /opt/echbay_vpssim/script/vpssim/module-nginx/${opensslversion}.tar.gz ]; then
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/${opensslversion}.tar.gz ${opensslversion}.tar.gz
else
wget -q --no-check-certificate https://www.openssl.org/source/${opensslversion}.tar.gz
fi
tar -xzxf ${opensslversion}.tar.gz
rm -rf ${opensslversion}.tar.gz

# $moduledir/${zlibversion}
rm -rf ${zlibversion}
#wget -q --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/${zlibversion}.tar.gz
if [ -f /opt/echbay_vpssim/script/vpssim/module-nginx/${zlibversion}.tar.gz ]; then
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/${zlibversion}.tar.gz ${zlibversion}.tar.gz
else
wget -q --no-check-certificate https://www.zlib.net/${zlibversion}.tar.gz
fi
tar -xzxf ${zlibversion}.tar.gz
rm -rf ${zlibversion}.tar.gz

wget -q --no-check-certificate https://github.com/cloudflare/zlib/archive/gcc.amd64.zip -O zlib-cloudflare.zip
unzip -oq zlib-cloudflare.zip
rm -rf zlib-cloudflare.zip

# /usr/local/vpssim/${pcreVersionInstall}
rm -rf ${pcreVersionInstall}
#wget -q --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/${pcreVersionInstall}.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/${pcreVersionInstall}.zip ${pcreVersionInstall}.zip
unzip -oq ${pcreVersionInstall}.zip
rm -rf ${pcreVersionInstall}.zip

# /usr/local/vpssim/ngx_http_redis-0.3.8
rm -rf ngx_http_redis-0.3.8
#wget -q --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/ngx_http_redis-0.3.8.tar.gz
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/ngx_http_redis-0.3.8.tar.gz ngx_http_redis-0.3.8.tar.gz
tar -xzxf ngx_http_redis-0.3.8.tar.gz
rm -rf ngx_http_redis-0.3.8.tar.gz

# /usr/local/vpssim/redis2-nginx-module
rm -rf redis2-nginx-module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/redis2-nginx-module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/redis2-nginx-module.zip redis2-nginx-module.zip
unzip -oq redis2-nginx-module.zip
rm -rf redis2-nginx-module.zip

# /usr/local/vpssim/set-misc-nginx-module
rm -rf set-misc-nginx-module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/set-misc-nginx-module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/set-misc-nginx-module.zip set-misc-nginx-module.zip
unzip -oq set-misc-nginx-module.zip
rm -rf set-misc-nginx-module.zip

# /usr/local/vpssim/ngx_devel_kit
rm -rf ngx_devel_kit*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/ngx_devel_kit.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/ngx_devel_kit.zip ngx_devel_kit.zip
unzip -oq ngx_devel_kit.zip
rm -rf ngx_devel_kit.zip

# /usr/local/vpssim/ngx_http_concat
rm -rf ngx_http_concat
#wget -q --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/ngx_http_concat.tar.gz
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/ngx_http_concat.tar.gz ngx_http_concat.tar.gz
tar -xzxf ngx_http_concat.tar.gz
rm -rf ngx_http_concat.tar.gz

# /usr/local/vpssim/srcache-nginx-module
rm -rf srcache-nginx-module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/srcache-nginx-module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/srcache-nginx-module.zip srcache-nginx-module.zip
unzip -oq srcache-nginx-module.zip
rm -rf srcache-nginx-module.zip

# /usr/local/vpssim/memc-nginx-module
rm -rf memc-nginx-module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/memc-nginx-module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/memc-nginx-module.zip memc-nginx-module.zip
unzip -oq memc-nginx-module.zip
rm -rf memc-nginx-module.zip

# /usr/local/vpssim/libatomic_ops-master
rm -rf libatomic_ops*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/libatomic_ops.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/libatomic_ops.zip libatomic_ops.zip
unzip -oq libatomic_ops.zip
rm -rf libatomic_ops.zip
# /usr/local/vpssim/nginx-module-vts-master
#rm -rf nginx_module_vts*
#wget -q https://vpssim.echbay.com/script/vpssim/module-nginx/nginx_module_vts.tar.gz
#tar -xzxf nginx_module_vts.tar.gz
#rm -rf nginx_module_vts.tar.gz



# thu nghiem voi ngx_brotli
/opt/echbay_vpssim/script/vpssim/menu/ngx_brotli-download




mkdir -p /usr/share/nginx/modules



