#!/bin/bash


moduledir=/usr/local/vpssim

#opensslversion=openssl-1.0.2h
#opensslversion=openssl-1.0.2l
opensslversion=openssl-1.0.2s

#zlibversion=zlib-1.2.8
zlibversion=zlib-1.2.11

#pcreVersionInstall=pcre-8.39
pcreVersionInstall=pcre-8.43

Nginx_VERSION=`cat /tmp/00-all-nginx-version.txt | awk 'NR==2 {print $1}' | sed 's/|//' | sed 's/|//'`
echo $Nginx_VERSION
exit


echo "=========================================================================="
echo "Download Nginx Module ... "
echo "=========================================================================="

urlForDownloadNginxModule="https://vpssim.echbay.com/script/vpssim/module-nginx/"


install_devtoolset_gcc () {
sudo yum -y install gcc-c++ pcre-devel zlib-devel

#sudo rpm --import https://linux.web.cern.ch/linux/scientific6/docs/repository/cern/slc6X/i386/RPM-GPG-KEY-cern
#sudo rpm --import ${urlForDownloadNginxModule}RPM-GPG-KEY-cern
sudo rpm --import /opt/echbay_vpssim/script/vpssim/module-nginx/RPM-GPG-KEY-cern

#sudo wget -O /etc/yum.repos.d/slc6-devtoolset.repo https://linux.web.cern.ch/linux/scientific6/docs/repository/cern/devtoolset/slc6-devtoolset.repo
#sudo wget -O /etc/yum.repos.d/slc6-devtoolset.repo ${urlForDownloadNginxModule}slc6-devtoolset.repo
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/slc6-devtoolset.repo /etc/yum.repos.d/slc6-devtoolset.repo

sudo yum -y install devtoolset-2-gcc-c++ devtoolset-2-binutils
}
install_devtoolset_gcc

if [ ! -d /opt/rh/devtoolset-2/root/usr/bin ]; then
	echo "Khong xac dinh duoc thu muc: /opt/rh/devtoolset-2/root/usr/bin (lan 1)"
	sleep 30
	install_devtoolset_gcc

	if [ ! -d /opt/rh/devtoolset-2/root/usr/bin ]; then
		echo "Khong xac dinh duoc thu muc: /opt/rh/devtoolset-2/root/usr/bin (lan 2)"
		sleep 60
		install_devtoolset_gcc

		if [ ! -d /opt/rh/devtoolset-2/root/usr/bin ]; then
			echo "Khong xac dinh duoc thu muc: /opt/rh/devtoolset-2/root/usr/bin (lan 3 - THOAT)"
			echo "Co the do mang hien tai khong on dinh, vui long thu cai dat lai sau"
			exit
		fi
	fi
fi

#
PS_NGX_EXTRA_FLAGS="--with-cc=/opt/rh/devtoolset-2/root/usr/bin/gcc"

cd /usr/local/vpssim

# /usr/local/vpssim/echo-nginx-module
rm -rf echo-nginx-module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/echo-nginx-module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/echo-nginx-module.zip echo-nginx-module.zip
unzip -oq echo-nginx-module.zip
rm -rf echo-nginx-module.zip
# /usr/local/vpssim/ngx_http_substitutions_filter_module
rm -rf ngx_http_substitutions_filter_module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/ngx_http_substitutions_filter_module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/ngx_http_substitutions_filter_module.zip ngx_http_substitutions_filter_module.zip
unzip -oq ngx_http_substitutions_filter_module.zip
rm -rf ngx_http_substitutions_filter_module.zip
# /usr/local/vpssim/ngx_cache_purge-master
rm -rf ngx_cache_purge*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/ngx_cache_purge.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/ngx_cache_purge.zip ngx_cache_purge.zip
unzip -oq ngx_cache_purge.zip

rm -rf ngx_cache_purge.zip
# /usr/local/vpssim/headers-more-nginx-module
rm -rf headers-more-nginx-module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/headers-more-nginx-module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/headers-more-nginx-module.zip headers-more-nginx-module.zip
unzip -oq headers-more-nginx-module.zip
rm -rf headers-more-nginx-module.zip
# /usr/local/vpssim/openssl-1.0.2h
rm -rf ${opensslversion}
#wget -q --no-check-certificate https://vpssim.com/script/vpssim/module-nginx/${opensslversion}.tar.gz
#wget -q --no-check-certificate https://www.openssl.org/source/${opensslversion}.tar.gz
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/${opensslversion}.tar.gz ${opensslversion}.tar.gz
tar -xzxf ${opensslversion}.tar.gz
rm -rf ${opensslversion}.tar.gz
# $moduledir/${zlibversion}
rm -rf ${zlibversion}
#wget -q --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/${zlibversion}.tar.gz
#wget -q --no-check-certificate https://www.zlib.net/${zlibversion}.tar.gz
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/${zlibversion}.tar.gz ${zlibversion}.tar.gz
tar -xzxf ${zlibversion}.tar.gz
rm -rf ${zlibversion}.tar.gz

# /usr/local/vpssim/${pcreVersionInstall}
rm -rf ${pcreVersionInstall}
#wget -q --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/${pcreVersionInstall}.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/${pcreVersionInstall}.zip ${pcreVersionInstall}.zip
unzip -oq ${pcreVersionInstall}.zip
rm -rf ${pcreVersionInstall}.zip

# /usr/local/vpssim/ngx_http_redis-0.3.8
rm -rf ngx_http_redis-0.3.8
#wget -q --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/ngx_http_redis-0.3.8.tar.gz
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/ngx_http_redis-0.3.8.tar.gz ngx_http_redis-0.3.8.tar.gz
tar -xzxf ngx_http_redis-0.3.8.tar.gz
rm -rf ngx_http_redis-0.3.8.tar.gz
# /usr/local/vpssim/redis2-nginx-module
rm -rf redis2-nginx-module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/redis2-nginx-module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/redis2-nginx-module.zip redis2-nginx-module.zip
unzip -oq redis2-nginx-module.zip
rm -rf redis2-nginx-module.zip
# /usr/local/vpssim/set-misc-nginx-module
rm -rf set-misc-nginx-module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/set-misc-nginx-module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/set-misc-nginx-module.zip set-misc-nginx-module.zip
unzip -oq set-misc-nginx-module.zip
rm -rf set-misc-nginx-module.zip
# /usr/local/vpssim/ngx_devel_kit
rm -rf ngx_devel_kit*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/ngx_devel_kit.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/ngx_devel_kit.zip ngx_devel_kit.zip
unzip -oq ngx_devel_kit.zip
rm -rf ngx_devel_kit.zip
# /usr/local/vpssim/ngx_http_concat
rm -rf ngx_http_concat
#wget -q --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/ngx_http_concat.tar.gz
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/ngx_http_concat.tar.gz ngx_http_concat.tar.gz
tar -xzxf ngx_http_concat.tar.gz
rm -rf ngx_http_concat.tar.gz
# /usr/local/vpssim/srcache-nginx-module
rm -rf srcache-nginx-module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/srcache-nginx-module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/srcache-nginx-module.zip srcache-nginx-module.zip
unzip -oq srcache-nginx-module.zip
rm -rf srcache-nginx-module.zip
# /usr/local/vpssim/memc-nginx-module
rm -rf memc-nginx-module*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/memc-nginx-module.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/memc-nginx-module.zip memc-nginx-module.zip
unzip -oq memc-nginx-module.zip
rm -rf memc-nginx-module.zip
# /usr/local/vpssim/libatomic_ops-master
rm -rf libatomic_ops*
#wget --no-check-certificate https://vpssim.echbay.com/script/vpssim/module-nginx/libatomic_ops.zip
yes | cp -rf /opt/echbay_vpssim/script/vpssim/module-nginx/libatomic_ops.zip libatomic_ops.zip
unzip -oq libatomic_ops.zip
rm -rf libatomic_ops.zip
# /usr/local/vpssim/nginx-module-vts-master
#rm -rf nginx_module_vts*
#wget -q https://vpssim.echbay.com/script/vpssim/module-nginx/nginx_module_vts.tar.gz
#tar -xzxf nginx_module_vts.tar.gz
#rm -rf nginx_module_vts.tar.gz
cd
cd /usr/local/vpssim
#cai dat nginx
wget -q http://nginx.org/download/nginx-${Nginx_VERSION}.tar.gz
tar -xzf nginx-${Nginx_VERSION}.tar.gz
rm -rf /usr/local/vpssim/nginx-${Nginx_VERSION}.tar.gz
cd /usr/local/vpssim/nginx-${Nginx_VERSION}
#sed -i 's/"Server: nginx"/"Server: Nginx-VPSSIM"/g' /usr/local/vpssim/nginx-${Nginx_VERSION}/src/http/ngx_http_header_filter_module.c
#sed -i 's/"Server: "/"Server: Nginx-VPSSIM"/g' /usr/local/vpssim/nginx-${Nginx_VERSION}/src/http/ngx_http_header_filter_module.c
./configure --prefix=/usr/share/nginx \
--sbin-path=/usr/sbin/nginx \
--group=nginx --user=nginx \
--pid-path=/var/run/nginx.pid \
--conf-path=/etc/nginx/nginx.conf \
--with-http_v2_module \
--with-http_ssl_module \
--with-ipv6 \
--with-http_flv_module \
--with-http_mp4_module \
--with-http_random_index_module \
--with-http_secure_link_module \
--with-http_stub_status_module \
--with-http_sub_module \
--with-http_xslt_module \
--with-http_addition_module \
--with-http_dav_module \
--with-http_geoip_module \
--with-http_image_filter_module \
--with-http_perl_module \
--with-mail \
--with-mail_ssl_module \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-file-aio \
--with-pcre=$moduledir/${pcreVersionInstall} \
--with-pcre-jit \
--with-google_perftools_module \
--with-debug \
--with-openssl=$moduledir/${opensslversion} \
--with-openssl-opt="enable-tlsext" \
--with-zlib=$moduledir/${zlibversion} \
--with-http_realip_module \
--with-http_stub_status_module \
--with-cc=/opt/rh/devtoolset-2/root/usr/bin/gcc \
--add-module=$moduledir/ngx_http_concat \
--add-module=$moduledir/ngx_cache_purge-master \
--add-module=$moduledir/ngx_devel_kit-master \
--add-module=$moduledir/set-misc-nginx-module-master \
--add-module=$moduledir/srcache-nginx-module-master \
--add-module=$moduledir/ngx_http_substitutions_filter_module-master \
--add-module=$moduledir/headers-more-nginx-module-master \
--add-module=$moduledir/ngx_http_redis-0.3.8
# cac module bi loi khi cai voi nginx
#--add-module=$moduledir/redis2-nginx-module-master \
#--add-module=$moduledir/echo-nginx-module-master \
#--add-module=$moduledir/memc-nginx-module-master \
make
make install
############################
# Download init & config file for nginx
rm -f /etc/init.d/nginx
download_initd_nginx () {
#wget --no-check-certificate -q https://vpssim.echbay.com/script/vpssim/nginx -O /etc/init.d/nginx && chmod +x /etc/init.d/nginx
yes | cp -rf /opt/echbay_vpssim/script/vpssim/nginx /etc/init.d/nginx && chmod +x /etc/init.d/nginx
}
download_initd_nginx
checkdownload_initd_nginx=`cat /etc/init.d/nginx`
if [ -z "$checkdownload_initd_nginx" ]; then
download_initd_nginx
fi
chmod +x /usr/sbin/nginx
rm -rf /etc/nginx/nginx.conf
mv /tmp/nginx.conf /etc/nginx/nginx.conf

echo "=========================================================================="
echo "Cai Dat Hoan Tat Nginx "
echo "=========================================================================="
#exit
sleep 5

# End Download init & config file for nginx
