#!/bin/bash

# install nginx Mainline version
sudo yum -y install nginx
sudo systemctl start nginx
sudo systemctl status nginx
sudo systemctl enable nginx

#
cat > "/etc/vpssim/nginx.version" <<END
Mainline
END
