#!/bin/bash
prompt="Lua chon cua ban (0-Thoat):" 
#options=( "Update System" "Update VPSSIM" "Change Nginx Version" "Change phpMyAdmin Version" "Upgrade MariaDB to 10.0 Version" "Change PHP Version" "Change VPSSIM Language" "Thoat")
#options=( "Update System" "Update VPSSIM" "Update Nginx" "Change phpMyAdmin Version" "Change PHP Version" "Change VPSSIM Language" "Update OpenSSL version" "Reset code form git" "List soft version")
options=( "Update System" "Update ECHBAY-VPSSIM" "Update Nginx" "Change phpMyAdmin Version" "Change PHP Version" "Update OpenSSL version" \
"Pull code form git" "Reset code form git" "List soft version" "Nginx quiche" "Auto update system")
printf "=========================================================================\n"
printf "                VPSSIM - Quan Ly VPS/Server by WebGiaRe.org \n"
printf "=========================================================================\n"
printf "                        Update / Upgrade Service \n"
printf "=========================================================================\n"


PS3="$prompt"
select opt in "${options[@]}" ; do 
 
    case "$REPLY" in


	1) /etc/vpssim/menu/update-he-thong;;
	2) /etc/vpssim/menu/nang-cap-scripts;;
	3) /etc/vpssim/menu/nang-cap-nginx;;
#	3) /etc/vpssim/menu/vpssim-befor-nang-cap-nginx;;
	4) /etc/vpssim/menu/vpssim-nang-cap-phpmyadmin;;
#	5) /etc/vpssim/menu/nang-cap-mariaDB/vpssim-before-nang-cap-mariadb;;
	5) clear && /etc/vpssim/menu/nangcap-php/vpssim-updown-php;;
#	6) clear && /etc/vpssim/menu/vpssim-thay-doi-ngon-ngu-menu;;
	6) clear && /etc/vpssim/menu/nang-cap-openssl;;
	7) clear && /etc/vpssim/menu/git-pull;;
	8) clear && /etc/vpssim/menu/git-reset;;
	9) clear && /etc/vpssim/menu/list-all-soft-version;;
	10) clear && /etc/vpssim/menu/nginx-quiche;;
	11) clear && /etc/vpssim/menu/auto-update-system;;
	0) clear && vpssim;;
        *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done



