#!/bin/bash
. /home/vpssim.conf

if [ ! -f /etc/pure-ftpd/pure-ftpd.conf ]; then
clear
echo "========================================================================= "
echo "FTP Server chua duoc cai dat "
echo "-------------------------------------------------------------------------"
echo "Ban phai cai dat chuc nang Setup FTP server truoc"
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi
echo "========================================================================="
echo "Su dung chuc nang nay de xem thong tin tai khoan FTP cua website"
echo "-------------------------------------------------------------------------"
echo -n "Nhap ten website [ENTER]: " 
read website
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "Ban nhap sai, vui long nhap lai!"
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Website $website khong ton tai tren he thong!"
echo "-------------------------------------------------------------------------"
echo "Ban hay nhap lai !"
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website co le khong phai la domain !!"
echo "-------------------------------------------------------------------------"
echo "Ban vui long nhap lai  !"
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi
if [ "$(pure-pw list | grep "/home/$website/")" == "" ]; then
clear
echo "========================================================================="
echo "Website $website chua tao tai khoan FTP !"
/etc/vpssim/menu/vpssim-ftpserver-menu
fi
echo "========================================================================="
echo "Tim thay $website tren he thong"
echo "-------------------------------------------------------------------------"
echo "$website da duoc tao tai khoan FTP"
echo "-------------------------------------------------------------------------"
echo "VPSSIM dang lay thong tin"
echo "-------------------------------------------------------------------------"
echo "Please wait...."
sleep 5
clear
echo "========================================================================="
echo "Thong tin login tai khoan FTP cua $website:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip"
echo "-------------------------------------------------------------------------"
echo "Username: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}') | Password: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $10}')"
/etc/vpssim/menu/vpssim-ftpserver-menu
