#!/bin/bash

#
/etc/vpssim/menu/centos9/option/tao-ftp-user-cho-domain

#
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then
/etc/vpssim/menu/vpssim-ftpserver-menu
else
/etc/vpssim/menu/centos9/option/ftpserver-menu
fi
