#!/bin/sh
. /home/vpssim.conf
if [ ! "$(redis-cli ping)" = "PONG" ]; then
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service redis start
else 
systemctl start redis.service
fi
clear
/etc/vpssim/menu/vpssim-redis-menu
else
/etc/vpssim/menu/vpssim-redis-menu
fi



