#!/bin/bash 
. /home/vpssim.conf
if [ ! -f ~/.ssh/id_rsa ]; then
ssh-keygen -f ~/.ssh/id_rsa -q -P ""
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
fi
if [ ! -f /usr/bin/sshpass ]; then
yum -y -q install sshpass
fi
if [ ! -f ~/.ssh/config ]; then
echo "StrictHostKeyChecking no" >> ~/.ssh/config
else
	if [ "`grep StrictHostKeyChecking ~/.ssh/config`" == "" ]; then
	echo "StrictHostKeyChecking no" >> ~/.ssh/config
	fi
fi
if [ ! -f /etc/vpssim/menu/vpssim-rsync-have-read ]; then
clear
printf "=========================================================================\n"
printf "               VPSSIM - Quan Ly VPS/Server by HostingAZ.VN \n"
printf "=========================================================================\n"
printf "                          Quan Ly VPS Backup \n"
printf "=========================================================================\n"
printf "\n"
echo "========================================================================="
echo "Su dung chuc nang nay de cai dat va cau hinh backup Server hien tai"
echo "-------------------------------------------------------------------------"
echo "sang VPS khac (VPS backup) bang Rsync. Viec sao luu du lieu server sang "
echo "-------------------------------------------------------------------------"
echo "VPS khac giup du lieu an toan hon la de truc tiep server dang su dung."
echo "-------------------------------------------------------------------------"
echo "Khi de du lieu backup tren VPS khac, du lieu backup van an toan ngay"
echo "-------------------------------------------------------------------------"
echo "ngay ca khi server dang su dung gap su co die hay khong cuu duoc du lieu."
echo "-------------------------------------------------------------------------"
echo "He dieu hanh VPS backup ho tro: Centos 6, Centos 7, Ubuntu, Debian. "
echo "-------------------------------------------------------------------------"
echo "VPSSIM khuyen dung Centos 6 de nhan ho tro nhieu nhat tu VPSSIM."
echo "-------------------------------------------------------------------------"
echo "Luu y: Ban co the su dung 1 VPS backup de sao luu nhieu VPS chay VPSSIM"
echo "-------------------------------------------------------------------------"
touch /etc/vpssim/menu/vpssim-rsync-have-read
read -p "Nhan [Enter] de tiep tuc ..."
clear
fi
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
