#!/bin/bash
# VPSSIM - Check VPS/Server Information
# Manage VPS/Server by EchBay.com

prompt="Lua chon cua ban (0-Thoat): "
options=(
  "Services dang chay va RAM dung"
  "RAM MySQL su dung"
  "Free Disc"
  "Uptime VPS"
  "CPU Load average"
  "Last YUM update"
  "Authentication Failures"
  "User dang nhap gan day"
  "Xem thong tin CPU"
  "Check I/O Speed"
  "Check download Speed"
)

printf "=========================================================================\n"
printf "                VPSSIM - Manage VPS/Server by EchBay.com                 \n"
printf "=========================================================================\n"
printf "                     Check VPS/Server Information                        \n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" "Thoat";
do
  case "$REPLY" in
    0)
      clear
      vpssim
    ;;
    1)
      clear
      echo "========================================================================="
      /etc/vpssim/menu/vpssim-tien-trinh-dang-chay-ram-use
    ;;
    2)
      /etc/vpssim/menu/checkddos/vpssim-ram-mysql-dung
    ;;
    3)
      /etc/vpssim/menu/checkddos/vpssim-dung-luong-disc-trong
    ;;
    4)
      /etc/vpssim/menu/checkddos/vpssim-uptime-vps
    ;;
    5)
      /etc/vpssim/menu/checkddos/vpssim-load-average
    ;;
    6)
      /etc/vpssim/menu/checkddos/vpssim-lan-cap-nhat-yum-cuoi
    ;;
    7)
      /etc/vpssim/menu/checkddos/vpssim-Authenication-Failures
    ;;
    8)
      /etc/vpssim/menu/checkddos/vpssim-user-dang-nhap-gan-day
    ;;
    9)
      echo "-------------------------------------------------------------------------"
      cat /proc/cpuinfo
      echo "-------------------------------------------------------------------------"
    ;;
    10)
      echo "-------------------------------------------------------------------------"
      echo "Testing I/O Speed..."
      dd if=/dev/zero of=/tmp/test_io_$$_ bs=64k count=16k conv=fdatasync 2>&1
      rm -f /tmp/test_io_$$_
      echo "-------------------------------------------------------------------------"
    ;;
    11)
      clear
      echo "Downloading and running benchmark script..."
      wget --no-check-certificate -q \
      https://raw.githubusercontent.com/itvn9online/vpssim-free/master/script/others/freeVPSbench.sh \
      -O - | bash
    ;;
    *)
      echo "Ban nhap sai, vui long nhap theo so thu tu tren menu!"
      continue
    ;;
  esac
done
