#!/bin/bash
. /home/vpssim.conf
if [ -f /etc/pure-ftpd/pure-ftpd.conf ]; then
clear
echo "========================================================================= "
echo "FTP server da duoc cai dat tren server. "
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi

clear
echo "========================================================================= "
echo "Chuan bi cai dat FTP Server... "
sleep 3
yum -y install pure-ftpd
sed -i 's/ChrootEveryone/#ChrootEveryone/g' /etc/pure-ftpd/pure-ftpd.conf
sed -i 's/VerboseLog/#VerboseLog/g' /etc/pure-ftpd/pure-ftpd.conf
sed -i 's/NoAnonymous/#NoAnonymous/g' /etc/pure-ftpd/pure-ftpd.conf
echo "
ChrootEveryone yes
UnixAuthentication yes
VerboseLog yes
CreateHomeDir yes
NoAnonymous yes
PureDB /etc/pure-ftpd/pureftpd.pdb
PassivePortRange          30000 50000
TLS 1
" >> /etc/pure-ftpd/pure-ftpd.conf ;

openssl req -x509 -nodes -days 7200 -newkey rsa:2048 -keyout /etc/pki/pure-ftpd/pure-ftpd.pem -out /etc/pki/pure-ftpd/pure-ftpd.pem -subj "/C=US/ST=VPSSIM FTP/L=VPSSIM FTP/O=VPSSIM FTP/CN=VPSSIM FTP"

if [ ! "$(grep /etc/ssl/private/pure-ftpd.pem /etc/pure-ftpd/pure-ftpd.conf)" == "" ]; then
echo "
TLSCipherSuite           HIGH
CertFile                 /etc/ssl/private/pure-ftpd.pem
" >> /etc/pure-ftpd/pure-ftpd.conf ;
if [ ! -d /etc/ssl/private ]; then
mkdir -p /etc/ssl/private
fi
yes | cp -rf /etc/pki/pure-ftpd/pure-ftpd.pem /etc/ssl/private/pure-ftpd.pem
fi
 
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
chkconfig pure-ftpd on
service pure-ftpd start
service pure-ftpd restart
else
systemctl enable pure-ftpd 
systemctl start pure-ftpd 
systemctl restart pure-ftpd 
fi
iptables -I INPUT 2 -p tcp --dport 30000:50000 -j ACCEPT
iptables -I INPUT 2 -p udp --dport 30000:50000 -j ACCEPT
iptables -I INPUT 2 -p tcp --dport 21 -j ACCEPT
iptables -I INPUT 2 -p udp --dport 21 -j ACCEPT
service iptables save
#chown -R nginx:nginx /home
if [ -f /etc/csf/csf.conf ]; then
clear
echo "-------------------------------------------------------------------------"
echo "Phat hien CSF FireWall dang duoc cai dat tren VPS"
echo "-------------------------------------------------------------------------"
echo "VPSSIM se khoi dong lai CSF Firewall ...."
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
sleep 5
/etc/vpssim/menu/CSF-Fiwall/vpssim-re-start-khoi-dong-lai-csf-lfd
fi
clear
echo "========================================================================= "
echo "Cai dat FTP server thanh cong"
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi

