#!/bin/sh
echo "Please wait....";sleep 1
clear
echo "========================================================================="
echo "Connections SYN_RECV: $(netstat -n | grep :80 | grep SYN_RECV|wc -l)"
/etc/vpssim/menu/vpssim-kiem-tra-ddos
