#!/bin/bash

echo "Install php module..."
#yum -y install php php-common php-fpm php-gd php-devel php-json
#yum -y install php-curl php-pecl-zip $phppeclredis php-zip php-soap php-cli php-ldap php-mysqlnd php-pear-Net-SMTP php-enchant php-mysql php-pear $memcachedinstall php-opcache php-pdo php-zlib php-xml php-mbstring php-mcrypt
sudo yum -y install php php-curl php-pecl-zip php-zip php-soap php-cli php-snmp php-pspell php-gmp php-ldap php-bcmath php-intl php-imap perl-libwww-perl perl-LWP-Protocol-https php-pear-Net-SMTP php-enchant php-common php-fpm php-gd php-devel php-mysql php-pear php-opcache php-pdo php-pgsql php-zlib php-xml php-mbstring php-mcrypt php-xmlrpc php-tidy

if [ -f /etc/redis/redis.conf ]; then
echo "Install php redis..."
#phppeclredis=php-pecl-redis
sudo yum -y install php-pecl-redis
fi

if [ -f /etc/sysconfig/memcached ]; then
echo "Install php memcache..."
#memcachedinstall=$(echo "php-pecl-memcached php-pecl-memcache")
sudo yum -y install php-pecl-memcached php-pecl-memcache
fi

clear
