#!/bin/bash

echo "change_php_config=1" > /tmp/change_php_config
echo "new_php_version=5.6" >> /tmp/change_php_config
echo "num_php_version=56" >> /tmp/change_php_config

/etc/vpssim/menu/nangcap-php/setup-php-7-global
