#!/bin/bash
. /home/vpssim.conf
random=`date |md5sum |cut -c '1-10'`
echo "-------------------------------------------------------------------------"
echo "Please wait ..."
sleep 1
echo "-------------------------------------------------------------------------"
if [ -f /var/log/nginx/error.log ]; then
minimumsize=1024000
 checksize=$(du -sb /var/log/nginx/error.log | awk 'NR==1 {print $1}')
	if [ "$checksize" = "0" ]; then
	clear
	echo "========================================================================= "
	echo "Khong co du lieu trong Nginx log file"
	/etc/vpssim/menu/vpssim-eroor-menu
	fi
	
	if [ $checksize -ge $minimumsize ]; then
	rm -rf /home/$mainsite/private_html/server-log/nginx.log*
	\cp -uf /var/log/nginx/error.log /home/$mainsite/private_html/server-log/
	cd /home/$mainsite/private_html/server-log
		sed -i '1s/^/========================================================================= \n\n/' error.log
	sed -i '2s/^/Nginx Log - Created by VPSSIM \n\n/' error.log
	sed -i '3s/^/========================================================================= \n\n/' error.log
	zip nginx.log-$random.zip error.log
	rm -rf error.log
	chmod -R 755 /home/$mainsite/private_html/server-log/*
	clear
	echo "========================================================================= "
	echo "Link download Log Nginx:"
	echo "-------------------------------------------------------------------------"
	echo "http://$serverip:$priport/server-log/nginx.log-$random.zip"
	/etc/vpssim/menu/vpssim-eroor-menu
  else
    rm -rf /home/$mainsite/private_html/server-log/nginx.log*
	\cp -uf /var/log/nginx/error.log /home/$mainsite/private_html/server-log/
	cd /home/$mainsite/private_html/server-log
	mv error.log nginx.log-$random.txt	
	sed -i '1s/^/========================================================================= \n\n/' nginx.log-$random.txt
	sed -i '2s/^/Nginx Log - Created by VPSSIM \n\n/' nginx.log-$random.txt
	sed -i '3s/^/========================================================================= \n\n/' nginx.log-$random.txt
	cd
	chmod -R 755 /home/$mainsite/private_html/server-log/*
	clear
	echo "========================================================================= "
	echo "Link Xem Nginx Log:"
	echo "-------------------------------------------------------------------------"
	echo "http://$serverip:$priport/server-log/nginx.log-$random.txt"
	/etc/vpssim/menu/vpssim-eroor-menu
  fi 
  
else
clear
echo "========================================================================= "
echo "File log khong ton tai hoac ban Disable chuc nang ghi log"
/etc/vpssim/menu/vpssim-eroor-menu
fi 

