#!/bin/bash 
. /home/vpssim.conf
if [ -f /etc/csf/csf.conf ]; then
clear
echo "========================================================================= "
echo "CSF Firewall da duoc cai dat tren server !"
/etc/vpssim/menu/vpssim-kiem-tra-ddos
else
echo "-------------------------------------------------------------------------"
echo "Install CSF Firewall...."
sleep 2
/etc/vpssim/menu/vpssim-cai-csf-firewall-cai-dat-CSF-FIREWALL

clear
if [ -f /etc/csf/csf.conf ]; then
clear
echo "========================================================================= "
echo "Cai dat va config thanh cong CSF Firewall tren server"
/etc/vpssim/menu/vpssim-kiem-tra-ddos
else
clear
echo "========================================================================= "
echo "Cai dat CSF Firewall that bai ! Ban vui long thu cai dat lai !"
/etc/vpssim/menu/vpssim-kiem-tra-ddos
fi
fi

