#!/bin/bash
prompt="Lua chon cua ban (8-Thoat):" 
options=( "Update System" "Update VPSSIM" "Change Nginx Version" "Change phpMyAdmin Version" "Upgrade MariaDB to 10.0 Version" "Change PHP Version" "Change VPSSIM Language" "Thoat")
printf "=========================================================================\n"
printf "                VPSSIM - Quan Ly VPS/Server by HostingAZ.VN \n"
printf "=========================================================================\n"
printf "                        Update / Upgrade Service \n"
printf "=========================================================================\n"


PS3="$prompt"
select opt in "${options[@]}" ; do 
 
    case "$REPLY" in


    1) /etc/vpssim/menu/update-he-thong;;
    2) /etc/vpssim/menu/vpssim-nang-cap-scripts;;
    3) /etc/vpssim/menu/vpssim-nang-cap-nginx;;
    4) /etc/vpssim/menu/vpssim-nang-cap-phpmyadmin;;
    5) /etc/vpssim/menu/nang-cap-mariaDB/vpssim-before-nang-cap-mariadb;;
    6) clear && /etc/vpssim/menu/nangcap-php/vpssim-updown-php;; 
    7) clear && /etc/vpssim/menu/vpssim-thay-doi-ngon-ngu-menu;; 
    8) clear && vpssim;;
        *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done



