#!/bin/bash 
. /home/vpssim.conf
version=3.1.9
echo "========================================================================="
echo "Them Domain + Tu dong cai dat PHPBB Forum $version"
echo "-------------------------------------------------------------------------"
echo "Sau khi them Domain vao server, Website cua ban san sang hoat dong ngay"
echo "-------------------------------------------------------------------------"
echo "Ban khong can cai dat thu cong PHPBB Forum nua."
echo "========================================================================="
echo -n "Nhap ten domain [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "Ban phaiNhap ten domain."
/etc/vpssim/menu/vpssim-them-website-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website co le khong dung dinh dang domain!"
echo "-------------------------------------------------------------------------"
echo "Vui long thu lai !"
/etc/vpssim/menu/vpssim-them-website-menu
exit
fi
if [ -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "$website da ton tai tren he thong"
echo "-------------------------------------------------------------------------"
echo "Vui long thu lai !"
/etc/vpssim/menu/vpssim-them-website-menu
exit
fi
echo "-------------------------------------------------------------------------"
echo -n "Nhap tai khoan Admin [ENTER]: " 
read adminphpbb
if [ "$adminphpbb" = "" ]; then
echo "========================================================================="
echo "Ban phai nhap ten tai khoan admin."
/etc/vpssim/menu/vpssim-them-website-menu
exit
fi
if [[ ! ${#adminphpbb} -ge 5 ]]; then
clear
echo "========================================================================="
echo "Tai khoan admin toi thieu co 5 ky tu "
echo "-------------------------------------------------------------------------"
echo "Vui long thu lai !"
/etc/vpssim/menu/vpssim-them-website-menu
exit
fi 
checkuseradmin="^[a-zA-Z0-9_][-a-zA-Z0-9_]{0,61}[a-zA-Z0-9_]$";
if [[ ! "$adminphpbb" =~ $checkuseradmin ]]; then
clear
echo "========================================================================="
echo "Ban chi duoc phep dung chu cai va so."
echo "-------------------------------------------------------------------------"
echo "Vui long thu lai  !"
/etc/vpssim/menu/vpssim-them-website-menu
exit
fi 
echo "-------------------------------------------------------------------------"
echo "Password for $adminphpbb toi thieu phai co 8 ky tu"
echo "-------------------------------------------------------------------------"
echo -n "Type in password for $adminphpbb [ENTER]: " 
read passphpbb
if [[ ! ${#passphpbb} -ge 8 ]]; then
clear
echo "========================================================================="
echo "Mat khau cho $adminphpbb toi thieu phai co 8 ky tu "
echo "-------------------------------------------------------------------------"
echo "Vui long thu lai !"
/etc/vpssim/menu/vpssim-them-website-menu
exit
fi 
echo "-------------------------------------------------------------------------"
echo "Prepare To Download and Install PHPBB Forum $version ..."
sleep 2
    mkdir -p "/home/$website/public_html"
    mkdir -p "/home/$website/logs"
    cd "/home/$website/public_html"
    wget https://www.phpbb.com/files/release/phpBB-$version.zip
    echo "-------------------------------------------------------------------------"
    echo "Download Finished. Start Installation ....."
    sleep 6  
    unzip -o phpBB-$version.zip
    mv -f phpBB3/* ./
    rm -rf phpBB-$version.zip
    rm -rf phpBB3
    cd

chown -R nginx:nginx "/home/$website/public_html/"
find "/home/$website/public_html/" -type d -exec chmod g+s {} \;
\cp -uf /etc/vpssim/menu/robots.txt "/home/$website/public_html/"
    cat > "/etc/nginx/conf.d/$website.conf" <<END
server {
	    server_name www.$website;
	    rewrite ^(.*) http://$website\$1 permanent;
    	}
server {
	    listen   80;
    	access_log off;
    	# access_log   /home/$website/logs/access_log;
    	error_log off;
    	# error_log /home/$website/logs/error.log;
    	add_header X-Frame-Options SAMEORIGIN;
		add_header X-Content-Type-Options nosniff;
		add_header X-XSS-Protection "1; mode=block";
		root /home/$website/public_html;
include /etc/nginx/conf/ddos2.conf;
	index index.php index.html index.htm;
    	server_name $website;
    	
#///////////////////////////////////////////////////////
# Ban chi co the chon 1 trong 4 rule AAA, BBB, CCC hoac DDD
# Ban nen comment cac rule khong su dung thay vi xoa chung vi neu ban su dung wordpress blog 
# Cac dong nay can thiet cho cac chuc nang trong Wordpress Blog Tools cua VPSSIM
# Thuat ngu:
# Comment - Them dau # vao truoc
# Uncomment - Bo dau # o truoc cau.
#///////////////////////////////////////////////////////


#Chay tat ca cac website (Wordpress, Xenforo, Joomla, Phpbb .... ). Neu ban su dung rule cua ban,comment dong duoi (them dau # vao truoc) (AAA)
include /etc/nginx/conf/all.conf;

#Neu ban su dung rule cua minh, comment rule o tren. Sau do uncoment (bo dau # ba dong duoi) sau do them rule vao giua. (BBB)
#location / {
#Uncomment 3 lines and set your rules here!
#}

# Rule cho wordpress + Plugin wp super cache. Neu ban su dung wordpress va wp super cache, uncomment dong duoi va comment dong AAA phia tren (CCC)
#include /etc/nginx/conf/supercache.conf;  

# Rule cho wordpress + Plugin W3 Total Cache. Neu ban su dung wordpress va W3 Total, uncomment dong duoi va comment dong AAA phia tren. (DDD)
#include /etc/nginx/conf/w3total.conf;  

# Confif Cache Static Files
include /etc/nginx/conf/staticfiles.conf;

#Tang bao mat security, chong sql injection  ....(uncoment neu ban muon su dung). Boi vi mot so code website khong su dung duoc voi rule nay, nen mac dinh VPSSIM de tat.
#Khong duoc xoa dong duoi, neu xoa VPSSIM se khong hoat dong !
#include /etc/nginx/conf/block.conf;
 
# Error Page
#error_page 403 /errorpage_html/403.html;
#error_page 404 /errorpage_html/404.html;
#error_page 405 /errorpage_html/405.html;
#error_page 502 /errorpage_html/502.html;
#error_page 503 /errorpage_html/503.html;
#error_page 504 /errorpage_html/504.html;
#location ^~ /errorpage_html/ {
#   internal;
#    root /home/$website;
#    access_log              off;
#}
    	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include /etc/nginx/fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
		fastcgi_connect_timeout 250;
		fastcgi_send_timeout 250;
		fastcgi_read_timeout 250;
		fastcgi_buffer_size 256k;
		fastcgi_buffers 4 256k;
		fastcgi_busy_buffers_size 256k;
		fastcgi_temp_file_write_size 256k;
		fastcgi_intercept_errors on;
        fastcgi_param SCRIPT_FILENAME /home/$website/public_html\$fastcgi_script_name;
    	}
	

#include /etc/nginx/conf/phpstatus.conf;
include /etc/nginx/conf/drop.conf;

    }
END
mkdir -p /home/$website/errorpage_html && cp -r /etc/vpssim/errorpage_html/*.html /home/$website/errorpage_html
   echo "$website" > /tmp/databasename.txt
#echo $website | sed "s/\./_/" | sed "s/\-/_/" | cut -c1-14  > /tmp/databasename.txt  
sed -i 's/\./_/g' /tmp/databasename.txt
sed -i 's/\-/_/g' /tmp/databasename.txt
random=`date |md5sum |cut -c '1-4'`
dataname=`cat /tmp/databasename.txt | cut -c1-11`_$random
username=`cat /tmp/databasename.txt | sed "s/\_//" | sed "s/\_//" | sed "s/\_//" | sed "s/\_//" | cut -c1-10`$random
password=`date |md5sum |cut -c '14-29'`
rm -rf /tmp/databasename.txt
cat > "/tmp/config.temp" <<END
CREATE DATABASE $dataname COLLATE utf8_general_ci;
END

mysql -u root -p$mariadbpass < /tmp/config.temp
rm -f /tmp/config.temp

 cat > "/tmp/config.temp" <<END
CREATE USER '$username'@'localhost' IDENTIFIED BY '$password';
END

	mysql -u root -p$mariadbpass < /tmp/config.temp
	rm -f /tmp/config.temp

    cat > "/tmp/config.temp" <<END
GRANT ALL PRIVILEGES ON $dataname . * TO '$username'@'localhost';
END
	mysql -u root -p$mariadbpass < /tmp/config.temp
	rm -f /tmp/config.temp

    cat > "/tmp/config.temp" <<END
FLUSH PRIVILEGES;
END
	mysql -u root -p$mariadbpass < /tmp/config.temp
	rm -f /tmp/config.temp

echo "=========================================================================" >> /home/DBinfo.txt
echo "Database: $dataname - Created on: $(date +%d/%m/%Y) when add $website to VPS" >> /home/DBinfo.txt
echo "=========================================================================" >> /home/DBinfo.txt
echo "Data name: $dataname" >> /home/DBinfo.txt
echo "Username: $username" >> /home/DBinfo.txt
echo "password: $password" >> /home/DBinfo.txt
echo "" >> /home/DBinfo.txt
cp -r /etc/vpssim/menu/database-example/database-example-phpbb.tar.gz  /tmp/database-example-phpbb.sql
cat > "/tmp/phpbbinstall" <<END
sed -i 's/useradmin/$adminphpbb/g' /tmp/database-example-phpbb.sql
sed -i 's/matkhauadmin/$(echo -n "$passphpbb" | md5sum | awk '{print $1}')/g' /tmp/database-example-phpbb.sql
sed -i 's/emailadmin/admin@$website/g' /tmp/database-example-phpbb.sql
sed -i 's/yourdomain.com/$website/g' /tmp/database-example-phpbb.sql
END
chmod +x /tmp/phpbbinstall
/tmp/phpbbinstall
mysql -u root -p$mariadbpass $dataname < /tmp/database-example-phpbb.sql
rm -rf /tmp/*phpbb*
rm -rf /home/$website/public_html/config.php
cat > "/home/$website/public_html/config.php" <<END
<?php
// phpBB 3.1.x auto-generated configuration file
// Do not change anything in this file!
\$dbms = 'phpbb\\\db\\\driver\\\mysqli';
\$dbhost = '';
\$dbport = '';
\$dbname = '$dataname';
\$dbuser = '$username';
\$dbpasswd = '$password';
\$table_prefix = 'phpbb_';
\$phpbb_adm_relative_path = 'adm/';
\$acm_type = 'phpbb\\\cache\\\driver\\\file';

@define('PHPBB_INSTALLED', true);
// @define('PHPBB_DISPLAY_LOAD_TIME', true);
// @define('DEBUG', true);
// @define('DEBUG_CONTAINER', true);
END
rm -rf /home/$website/public_html/install
chown -R nginx:nginx /home/$website/public_html/
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
service php-fpm restart
else 
systemctl reload nginx
systemctl restart php-fpm.service
fi
clear
echo "========================================================================="
echo "Them $website vao server & cai dat PhpBB code thanh cong "
echo "-------------------------------------------------------------------------"
echo "Admin Info: User: $adminphpbb | Password: $passphpbb"
echo "-------------------------------------------------------------------------"
echo "Email: admin@$website"
echo "-------------------------------------------------------------------------"
echo "Dang nhap & thay Email cho $adminphpbb trong PhpBB admin"
echo "-------------------------------------------------------------------------"
echo "Vhost File: /etc/nginx/conf.d/$website.conf"
echo "-------------------------------------------------------------------------"
echo "Thong tin Database duoc luu tai: /home/DBinfo.txt"
/etc/vpssim/menu/vpssim-them-website-menu
