#!/bin/sh
prompt="Lua chon cua ban (12-Thoat):"
options=("Services dang chay va RAM dung" "RAM MySQL su dung" "Free Disc " "Uptime VPS" "CPU Load average" "Last YUM update" "Authenication Failures" "User dang nhat gan day" "Xem thong tin CPU" "Check I/O Speed" "Check download Speed")
printf "=========================================================================\n"
printf "                VPSSIM - Manage VPS/Server by HostingAZ.VN             \n"
printf "=========================================================================\n"
printf "                     Check VPS/Server information\n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
    1) clear && echo "=========================================================================" && /etc/vpssim/menu/vpssim-tien-trinh-dang-chay-ram-use;;
    2) /etc/vpssim/menu/checkddos/vpssim-ram-mysql-dung;;
    3) /etc/vpssim/menu/checkddos/vpssim-dung-luong-disc-trong;;
    4) /etc/vpssim/menu/checkddos/vpssim-uptime-vps;;
    5) /etc/vpssim/menu/checkddos/vpssim-load-average;;
    6) /etc/vpssim/menu/checkddos/vpssim-lan-cap-nhat-yum-cuoi;;
    7) /etc/vpssim/menu/checkddos/vpssim-Authenication-Failures;;
    8) /etc/vpssim/menu/checkddos/vpssim-user-dang-nhap-gan-day;;
    9) echo "-------------------------------------------------------------------------" && cat /proc/cpuinfo && echo "-------------------------------------------------------------------------";;
    10) echo "-------------------------------------------------------------------------" && dd if=/dev/zero of=test bs=64k count=16k conv=fdatasync; rm test && echo "-------------------------------------------------------------------------";;
    11) clear && wget http://hostingaz.vn/script/others/freeVPSbench.sh -O - -o /dev/null|bash;;
$(( ${#options[@]}+1 )) ) echo "Bye!";  clear && /bin/vpssim;;
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac
done
