#!/bin/sh
. /home/vpssim.conf

if [ -f /etc/vpssim/net2ftpsite.info ]; then
net2ftpsite=$(cat /etc/vpssim/net2ftpsite.info)
 if [ ! -d /home/$net2ftpsite/public_html ]; then
rm -rf /etc/vpssim/net2ftpsite.info
 fi
fi

if [ -f /etc/vpssim/net2ftpsite.info ]; then
net2ftpsite=$(cat /etc/vpssim/net2ftpsite.info)
checknet2ftpconfig=$(grep auth_basic /etc/nginx/conf.d/$net2ftpsite.conf)
if [ "$checknet2ftpconfig" == "" ]; then
Protection=Disable
else
Protection=Enable
fi
fi

show_menu_net2ftp () {
prompt="Lua chon cua ban (6-Thoat):"
options=("Setup Net2FTP" "Cau hinh Upload Max Filesize" "Bao Ve Net2FTP" "Thay Domain Net2FTP          "  "Remove Net2FTP         " "Thoat")
printf "=========================================================================\n"
printf "                VPSSIM - Quan Ly VPS/Server by HostingAZ.VN \n"
printf "=========================================================================\n"
printf "                            Quan Ly Net2FTP \n"
printf "=========================================================================\n"
if [ ! -f /etc/vpssim/net2ftpsite.info ]; then
printf "                      Net2FTP status: Not Install \n"
else
printf "              Net2FTP status: Installed | Protection: $Protection\n"
fi
printf "=========================================================================\n"
if [ -f /etc/vpssim/net2ftpsite.info ]; then
net2ftpsite=$(cat /etc/vpssim/net2ftpsite.info)
printf "Link Net2FTP: http://$net2ftpsite\n"
printf "=========================================================================\n"
fi
PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) /etc/vpssim/menu/vpssim-cai-dat-net2ftp;;
    2) /etc/vpssim/menu/vpssim-change-upload-file-size-limit-net2ftp;;
    #2) /etc/vpssim/menu/vpssim-tat-bat-net2ftp;;
    #3) /etc/vpssim/menu/vpssim-thong-tin-quan-ly-net2ftp;;
    3) /etc/vpssim/menu/vpssim-mat-khau-bao-ve-net2ftp;; 
    4) /etc/vpssim/menu/vpssim-thay-domain-net2ftp;;
    5) /etc/vpssim/menu/vpssim-xoa-website-net2ftp;;
    6) clear && /bin/vpssim;;
    
  *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done
}

check_nginx_service () {
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
show_menu_net2ftp 
	else
clear
echo "========================================================================"
echo "Nginx service is not running"
echo "------------------------------------------------------------------------"
echo "VPSSIM trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
service nginx start
clear
echo "========================================================================"
echo "Check Nginx service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
		if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
show_menu_net2ftp 
		else
				clear
echo "========================================================================"
echo "VPSSIM can not start Nginx Service"
sleep 4 ;
	clear
	echo "========================================================================="
	echo "Rat tiec, Nginx dang stopped. Hay bat len truoc khi dung chuc nang nay!"
	vpssim
		fi
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
	if [ "`systemctl is-active nginx.service`" == "active" ]; then
show_menu_net2ftp 
	else
clear
echo "========================================================================"
echo "Nginx service is not running"
echo "------------------------------------------------------------------------"
echo "VPSSIM trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
systemctl start nginx.service
clear
echo "========================================================================"
echo "Check Nginx service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
	if [ "`systemctl is-active nginx.service`" == "active" ]; then
show_menu_net2ftp 
		else
				clear
echo "========================================================================"
echo "VPSSIM can not start Nginx Service"
sleep 4 ;
	clear
	echo "========================================================================="
	echo "Rat tiec, Nginx dang stopped. Hay bat len truoc khi dung chuc nang nay!"
	vpssim
		fi
fi
fi
}
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $5}')" == "running..." ]; then
check_nginx_service
	else
clear
echo "========================================================================"
echo "PHP-FPM service is not running"
echo "------------------------------------------------------------------------"
echo "VPSSIM trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
	echo "-------------------------------------------------------------------------"
service php-fpm start
clear
echo "========================================================================"
echo "Check PHP-FPM service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
			if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $5}')" == "running..." ]; then
check_nginx_service
		else
		clear
echo "========================================================================"
echo "VPSSIM can not start PHP-FPM Service"
sleep 4 ;
	clear
	echo "========================================================================="
	#echo "Sorry, PHP-FPM stopped. Start it before use this function!"
	echo "Sorry, PHP-FPM dang stopped. Hay bat len truoc khi dung chuc nang nay!"
	vpssim
		fi
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ "`systemctl is-active php-fpm.service`" == "active" ]; then
check_nginx_service
	else
clear
echo "========================================================================"
echo "PHP-FPM service is not running"
echo "------------------------------------------------------------------------"
echo "VPSSIM trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
	echo "-------------------------------------------------------------------------"
systemctl start php-fpm.service
clear
echo "========================================================================"
echo "Check PHP-FPM service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
if [ "`systemctl is-active php-fpm.service`" == "active" ]; then
check_nginx_service
		else
		clear
echo "========================================================================"
echo "VPSSIM can not start PHP-FPM Service"
sleep 4 ;
	clear
	echo "========================================================================="
	#echo "Sorry, PHP-FPM stopped. Start it before use this function!"
	echo "Sorry, PHP-FPM dang stopped. Hay bat len truoc khi dung chuc nang nay!"
	vpssim
		fi
fi
fi

