#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="
echo "Su dung chuc nang nay de fix loi [Missed Schedule] cho WP Website" 
echo "-------------------------------------------------------------------------"
echo "VPSSIM se cai dat plugin: [WP Missed Schedule] cho WP website va tu dong"
echo "-------------------------------------------------------------------------"
echo "BAT no. Plugin nay se chay 5 phut 1 lan va tu dong republish nhung post "
echo "-------------------------------------------------------------------------"
echo "bi loi Missed Schedule nhung gan nhu khong tieu ton tai nguyen server."
echo "========================================================================="
echo -n "Nhap ten website [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "Ban nhap sai, vui long nhap chinh xac."
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website co the khong dung dinh dang domain"
echo "-------------------------------------------------------------------------"
echo "Ban vui long thu lai !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "$website khong ton tai tren he thong"
echo "-------------------------------------------------------------------------"
echo "Ban vui long thu lai !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website khong su dung wordpress code hoac chua cai dat!"
echo "-------------------------------------------------------------------------"
echo "Vui long cai dat wordpress code truoc hoac nhap domain khac"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi

if [ -d /home/$website/public_html/wp-content/plugins/wp-missed-schedule ]; then
clear
echo "========================================================================="
echo "Ban da cai dat plugin wp-missed-schedule cho $website!"
echo "-------------------------------------------------------------------------"
echo "Hay acctive neu ban dang Disable no."
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi

echo "========================================================================="
read -r -p "Ban muon fix loi Missed Schedule cho $website ?  [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait..."    		
    sleep 1
cd /tmp
rm -rf /tmp/wp-missed-schedule.zip
wget -q --no-check-certificate https://vpssim.com/script/vpssim/Softwear/wp-missed-schedule.zip
if [ ! -f /tmp/wp-missed-schedule.zip ]; then
wget -q --no-check-certificate https://vpssim.com/script/vpssim/Softwear/wp-missed-schedule.zip
fi
unzip -q wp-missed-schedule.zip -d /home/$website/public_html/wp-content/plugins/
rm -rf /tmp/wp-missed-schedule.zip
chown -R nginx:nginx /home/$website/public_html/wp-content/plugins/wp-missed-schedule/*
cd /home/$website/public_html
/etc/vpssim/menu/vpssim-enable-tat-ca-cac-ham-php-php.ini
wp plugin activate wp-missed-schedule --allow-root
/etc/vpssim/menu/vpssim-re-config-cac-ham-php-disable-php.ini
cd
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service php-fpm restart
else
systemctl restart php-fpm.service
fi
clear
echo "========================================================================="
if [ -d /home/$website/public_html/wp-content/plugins/wp-missed-schedule ]; then
echo "Fix loi Missed Schedule cho $website thanh cong !"
else
echo "Fix loi Missed Schedule chua hoan thanh !"
echo "-------------------------------------------------------------------------"
echo "Ban vui long thu lai!"
fi
/etc/vpssim/menu/vpssim-wordpress-tools-menu
        ;;
    *)
       clear
    echo "========================================================================="
   echo "Cancel !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
        ;;
esac
exit
