#!/bin/bash 
. /home/vpssim.conf
if [ ! -f /etc/vpssim/vps_backup_rsync.info ]; then
clear
echo "========================================================================="
echo "Server hien tai chua duoc ket noi voi VPS backup"
echo "-------------------------------------------------------------------------"
echo "Ban khong can chay chuc nang nay."
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
exit
fi

ipvpsbackup=$(grep "ipaddress" /etc/vpssim/vps_backup_rsync.info | awk '{print $3}')
echo "========================================================================="
echo "Su dung chuc nang nay Ngat Ket noi va Disable Auto backup toi VPS Backup"
echo "-------------------------------------------------------------------------"
echo "Sau khi ngat ket noi, du lieu tren VPS Backup duoc du nguyen"
echo "-------------------------------------------------------------------------"
echo "Neu muon tiep tuc backup, ban phai Ket Noi va config lai"
echo "-------------------------------------------------------------------------"
read -r -p "Ban muon ngat ket noi toi VPS Backup ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait ... "
    sleep 3
pkill rync
rm -rf ~/.ssh/id_rsa.pub
rm -rf ~/.ssh/id_rsa
echo "sed -i '/$ipvpsbackup/d' ~/.ssh/known_hosts" > /tmp/knownhost_sedit
chmod +x /tmp/knownhost_sedit
/tmp/knownhost_sedit
rm -rf /tmp/knownhost_sedit
rm -rf /etc/vpssim/vps_backup_rsync.info
rm -rf /etc/vpssim/vpssim_backup_VPS_by_rsync 
rm -rf /etc/cron.d/vpssim.rsync.cron  
service crond restart
clear
echo "========================================================================="
echo "Ngat ket noi voi VPS backup thanh cong! "
  /etc/vpssim/menu/vpssim-befor-rsync
    ;;
*)
clear
echo "========================================================================="
echo "Ban huy disable backup by Rsync !"
  /etc/vpssim/menu/vpssim-rsync-backup-vps-menu
  exit
;;
esac
exit
