#!/bin/bash 
. /home/vpssim.conf
if [ -f /etc/vpssim/uploadsite ]; then
clear
echo "========================================================================="
echo "Ban da cai dat File Manager cho server !"
echo "-------------------------------------------------------------------------"
echo "Domain File Manager la: $(cat /etc/vpssim/uploadsite)"
echo "-------------------------------------------------------------------------"
echo "Hay tro $(cat /etc/vpssim/uploadsite) toi $serverip"
echo "-------------------------------------------------------------------------"
echo "va truy cap domain nay tren trinh duyet de quan ly file tren server"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi
echo "========================================================================="
echo "Su dung chuc nang nay de cai dat Domain File Manager cho server"
echo "-------------------------------------------------------------------------"
echo "Domain File Manager phai la domain moi, chua duoc add vao he thong"
echo "-------------------------------------------------------------------------"
echo "Ban nen su dung Sub-domain cho Domain File Manager"
echo "-------------------------------------------------------------------------"
echo -n "Nhap ten Domain [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "Ban nhap sai, vui long nhap lai!"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi

kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,12}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website co le khong phai la domain !!"
echo "-------------------------------------------------------------------------"
echo "Ban vui long thu lai  !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi

if [ -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Phat hien $website da ton tai tren he thong!"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi

#############
echo "-------------------------------------------------------------------------"
echo -n "Nhap tai khoan admin [ENTER]: " 
read adminupload
if [ "$adminupload" = "" ]; then
echo "========================================================================="
echo "Ban phai nhap tai khoan admin."
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi
if [[ ! ${#adminupload} -ge 5 ]]; then
clear
echo "========================================================================="
echo "User admin toi thieu phai co 5 ki tu "
echo "-------------------------------------------------------------------------"
echo "Ban vui long thu lai !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi 
checkuseradmin="^[a-zA-Z0-9_][-a-zA-Z0-9_]{0,61}[a-zA-Z0-9_]$";
if [[ ! "$adminupload" =~ $checkuseradmin ]]; then
clear
echo "========================================================================="
echo "Ban chi duoc su dung chu cai va so cho user admin"
echo "-------------------------------------------------------------------------"
echo "Ban vui long thu lai  !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi 

echo "-------------------------------------------------------------------------"
echo -n "Nhap mat khau admin [ENTER]: "
read matkhau
if [ "$matkhau" = "" ]; then
clear
echo "========================================================================="
echo "Ban chua nhap mat khau"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi
#checkpass="^[a-zA-Z0-9_][-a-zA-Z0-9_]{0,61}[a-zA-Z0-9_]$";
#if [[ ! "$matkhau" =~ $checkpass ]]; then
#clear
#echo "========================================================================="
#echo "Ban chi duoc dung chu cai va so de dat mat khau."
#echo "-------------------------------------------------------------------------"
#echo "Ban vui long thu lai  !"
#/etc/vpssim/menu/vpssim-web-upload-menu
#exit
#fi
if [[ ! ${#matkhau} -ge 8 ]]; then
clear
echo "========================================================================="
echo "Mat khau toi thieu phai co 8 ky tu "
echo "-------------------------------------------------------------------------"
echo "Ban vui long thu lai  !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi 
#######



echo "$website" > /etc/vpssim/uploadsite
echo "========================================================================="
echo "Chuan bi cai dat File Manage cho $website"
echo "-------------------------------------------------------------------------"
echo "De bao mat, cac Search Engine se bi chan khi ket noi toi $website" 
echo "-------------------------------------------------------------------------"
echo "$website se khong xuat hien tren Google, bing..."
sleep 10
    mkdir -p "/home/$website/public_html"
    mkdir -p "/home/$website/logs"
    cd /home/$website/public_html
wget --no-check-certificate -q https://hostingaz.vn/script/vpssim/eXtplorer/eXtplorer_2.1.9.zip
unzip -q eXtplorer_2.1.9.zip
rm -rf eXtplorer_2.1.9.zip
echo "please wait... "; sleep 2
cd
rm -rf /home/$website/public_html/config/.htusers.php
cat > "/home/$website/public_html/config/.htusers.php" <<END
<?php
        // ensure this file is being included by a parent file
        if( !defined( '_JEXEC' ) && !defined( '_VALID_MOS' ) ) die( 'Restricted access' );
        \$GLOBALS["users"]=array(
        array('$adminupload','$(echo -n $matkhau | md5sum | cut -d" " -f1)','/home','http://localhost','1','','7',1),
);
?>
END

cat > "/home/$website/public_html/robots.txt" <<END
User-agent: *
Disallow: /
END

chown -R nginx:nginx /home/$website/public_html/
    cat > "/etc/nginx/conf.d/$website.conf" <<END
server {
	    server_name www.$website;
	    rewrite ^(.*) http://$website\$1 permanent;
    	}
server {
	    listen   80;
    	access_log off;
    	error_log off;
    	# error_log /home/$website/logs/error.log;
    	root /home/$website/public_html;
include /etc/nginx/conf/ddos2.conf;
 	index index.php index.html index.htm;
    	server_name $website;
    	

#///////////////////////////////////////////////////////
#///////////////////////////////////////////////////////
include /etc/nginx/conf/supercache.conf;  

#Tang bao mat security, chong sql injection  ....(uncoment neu ban muon su dung). Boi vi mot so code website khong su dung duoc voi rule nay, nen mac dinh VPSSIM de tat.
#include /etc/nginx/conf/block.conf;

    	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
        	include /etc/nginx/fastcgi_params;
        	fastcgi_pass 127.0.0.1:9000;
        	fastcgi_index index.php;
		fastcgi_connect_timeout 2000;
		fastcgi_send_timeout 2000;
		fastcgi_read_timeout 2000;
		fastcgi_buffer_size 256k;
		fastcgi_buffers 4 256k;
		fastcgi_busy_buffers_size 256k;
		fastcgi_temp_file_write_size 256k;
		fastcgi_intercept_errors on;
        	fastcgi_param SCRIPT_FILENAME /home/$website/public_html\$fastcgi_script_name;
    	}
    	
include /etc/nginx/conf/staticfiles.conf;
#include /etc/nginx/conf/phpstatus.conf;
include /etc/nginx/conf/drop.conf;
#include /etc/nginx/conf/errorpage.conf;
    }
END
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
service php-fpm restart
else 
systemctl reload nginx
systemctl restart php-fpm.service
fi
clear

echo "========================================================================="
echo "Hay tro domain $(cat /etc/vpssim/uploadsite) toi $serverip"
echo "-------------------------------------------------------------------------"
echo "va truy cap domain nay tren trinh duyet de quan ly file tren server."
echo "========================================================================="
echo "Thong tin quan ly: User: $adminupload | Password: $matkhau "
/etc/vpssim/menu/vpssim-web-upload-menu
