#!/bin/bash

# setup varnish disk cache config
yes | cp -rf /etc/vpssim/menu/varnish/sysconfig.txt -O /etc/sysconfig/varnish
chmod 644 /etc/sysconfig/varnish

# xoa dong dung luong cu
sed -i '/VARNISH_STORAGE_SIZE=/d' /etc/sysconfig/varnish

# thay bang dong moi
checktruenumber='^[0-9]+$'

# lay dung luong theo cau hinh cua nguoi dung
if [ -f /etc/vpssim/varnish.storage ]; then
varnish_size=$(cat /etc/vpssim/varnish.storage)
else

# tinh dung luong varnish cache dang su dung
if [ -f /var/lib/varnish/varnish_storage.bin ]; then
#ls -l /var/lib/varnish/varnish_storage.bin
#ls -l --b=M /var/lib/varnish/varnish_storage.bin | cut -d " " -f5
current_varnish_storage=$(ls -l /var/lib/varnish/varnish_storage.bin | cut -d " " -f5)
#echo $current_varnish_storage
current_varnish_storage=$(($current_varnish_storage/1024/1024/1024))
#echo $current_varnish_storage
else
current_varnish_storage=0
fi

# tinh toan dung luong o dia con dung
disfree=$(calc $(df $PWD | awk '/[0-9]%/{print $(NF-2)}')/1024)
echo "Disk free: "$disfree
diskrecommended=$(($disfree/1024))
#echo "Disk cache recommended: "$diskrecommended

varnish_size=$(($current_varnish_storage+$diskrecommended))
#echo $varnish_size
varnish_size=$(($varnish_size-3))
#echo $varnish_size
echo "Disk cache recommended: "$varnish_size

fi

if ! [[ $varnish_size =~ $checktruenumber ]] ; then
varnish_size=12
fi

echo "VARNISH_STORAGE_SIZE="$varnish_size"G" >> /etc/sysconfig/varnish
