#!/bin/bash

# https://packagecloud.io/varnishcache/
# https://packagecloud.io/varnishcache/varnish60/install#bash-rpm

curl -s https://packagecloud.io/install/repositories/varnishcache/varnish60/script.rpm.sh | sudo bash
sleep 2
sudo yum -y install varnish

if [ "$current_os_version" == "6" ]; then
service varnish start
chkconfig varnish on
else
systemctl start varnish.service
systemctl enable varnish.service
fi

varnishd -V

/etc/vpssim/menu/varnish/install-varnish
