#!/bin/bash

# https://packagecloud.io/varnishcache/
# https://packagecloud.io/varnishcache/varnish40/install#bash-rpm

/etc/vpssim/menu/varnish/install-varnish-begin
echo "4.0" >> /etc/vpssim/varnish.version

curl -s https://packagecloud.io/install/repositories/varnishcache/varnish40/script.rpm.sh | sudo

/etc/vpssim/menu/varnish/install-varnish-end
