#!/bin/bash

# https://packagecloud.io/varnishcache/
# https://packagecloud.io/varnishcache/varnish63/install#bash-rpm

/etc/vpssim/menu/varnish/install-varnish-begin
echo "6.3" >> /etc/vpssim/varnish.version

curl -s https://packagecloud.io/install/repositories/varnishcache/varnish63/script.rpm.sh | sudo bash

/etc/vpssim/menu/varnish/install-varnish-end
