#!/bin/bash
. /home/vpssim.conf

#
website=$1
installdemo=$2

cd ~

if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "Khong xac dinh duoc website can cai dat!"
/etc/vpssim/menu/centos9/option/them-website-menu
exit
fi

if [ ! -d /home/$website ]; then
clear
echo "========================================================================="
echo "Khong xac dinh duoc thu muc can cai dat!"
/etc/vpssim/menu/centos9/option/them-website-menu
exit
fi

# cài đặt wp-cli để cài đặt wordpress cho nó nhanh
if [ ! -f /usr/local/bin/wp ]; then
echo "========================================================================="
echo "Installing  WP-CLI" ;
wget -q --no-check-certificate https://raw.echbay.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
chmod +x wp-cli.phar
mv wp-cli.phar /usr/local/bin/wp
fi

#
cd /home/$website/public_html

#
if [ -f /tmp/vpssim-lastdb.txt ]; then
username=`cat /tmp/vpssim-lastdb.txt`
else
username=""
fi

#
if [ -f /tmp/vpssim-lastpassdb.txt ]; then
password=`cat /tmp/vpssim-lastpassdb.txt`
else
password=""
fi

# sử dụng wp-cli để tải wordpress
wp core download
if [ ! "$username" = "" ] && [ ! "$password" = "" ]; then
    # tạo file config luôn và ngay
    wp core config --dbname=$username --dbuser=$username --dbpass=$password

    if [ ! "$installdemo" = "" ]; then
    admin_user="admindemo"
    admin_pass=`date |md5sum |cut -c '1-16'`

    wp core install --url='http://'$website --title='Blog demo by ECHBAY-VPSSIM' --admin_user=$admin_user --admin_password=$admin_pass --admin_email='admin@'$website

    #
echo "$admin_user" > /tmp/vpssim-lastadmin.txt
echo "$admin_pass" > /tmp/vpssim-lastpassadmin.txt

    #
/etc/vpssim/menu/centos9/inc/them-website-after $website

    fi
else
yes | cp -rf wp-config-sample.php wp-config.php
fi

#
cd ~
