#!/bin/bash
. /home/vpssim.conf

#
website=$1
username=$2
password=$3

# remove old password before insert
sed -i -e "/$username/d" /etc/vpssim/FTP-Account.info
# insert new password
echo "FTP Account for $website | Username: $username | Password: $password | dd /home/$website/ " >> /etc/vpssim/FTP-Account.info

#
clear
echo "=========================================================================" 
echo "Tao tai khoan FTP cho $website thanh cong"
echo "-------------------------------------------------------------------------"
echo "Thong tin login:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip "
echo "-------------------------------------------------------------------------"
echo "User: $username | Password: $password"
