#!/bin/bash

#
echo "========================================================================="
echo "Danh sach website tren server/ List Website in Server"
echo "-------------------------------------------------------------------------"

#
rm -rf /tmp/domain_number*

#
stt=0
has_domain=""

#
for get_d in /home/*
do
	if [ -d $get_d ]; then
		website=$(basename $get_d)
		if [ ! "$website" = "vpssim.demo" ]; then
			# phải có vHost thì mới là 1 website hợp lệ
			if [ -f "/etc/nginx/conf.d/$website.conf" ]; then
				echo $stt". "$website
				
				# lưu domain vào để người dùng có bấm số chọn thì sẽ lấy được luôn domain để xử lý
				echo "$website" > "/tmp/domain_number$stt.txt"

				#
				let "stt+=1"
				has_domain="yes"
			else
				echo "ERROR! "$website" (ERROR: vHost not found)"
			fi
		fi
	fi
done

#
if [ "$has_domain" = "" ]; then
echo "Khong co domain nao duoc tim thay"
fi

#
echo "-------------------------------------------------------------------------"
