#!/bin/bash

#
echo "========================================================================="
echo "Danh sach website tren server"
echo "-------------------------------------------------------------------------"

#
stt=0

#
for get_d in /home/*
do
	if [ -d $get_d ]; then
		website=$(basename $get_d)
		if [ ! "$website" = "vpssim.demo" ]; then
			if [ -f "/etc/nginx/conf.d/$website.conf" ]; then
				echo $stt". "$website
			else
				echo $stt". "$website" (ERROR: vHost not found)"
			fi
			
			# lưu domain vào để người dùng có bấm số chọn thì sẽ lấy được luôn domain để xử lý
			echo "$website" > "/tmp/domain_number$stt.txt"

			#
			let "stt+=1"
		fi
	fi
done

#
echo "-------------------------------------------------------------------------"
