#!/bin/sh
. /home/vpssim.conf
ramzenduse=$(grep opcache.memory_consumption /etc/php.d/opcache.ini | grep -o '[0-9]*')
maxphpzen=$(grep opcache.max_accelerated_files /etc/php.d/opcache.ini | grep -o '[0-9]*')
cleartime=$(grep opcache.revalidate_freq /etc/php.d/opcache.ini | grep -o '[0-9]*')
prompt="Nhap lua chon cua ban (6-Thoat):"
options=("Tat Opcache" "Cau Hinh Zend Opcache" "Them Website Vao BlackList" "Xoa Website Khoi Blacklist" "Clear Zend OPcache")
printf "=========================================================================\n"
printf "                VPSSIM - Quan Ly VPS/Server by HostingAZ.VN \n"
printf "=========================================================================\n"
printf "                      Quan Ly Zend OPcache (Enable)\n"
printf "=========================================================================\n"
echo "  RAM Usage: $ramzenduse MB - Max Files: $maxphpzen - Auto Clear Time: $cleartime seconds" 
printf "=========================================================================\n"
printf "Zend Opcache Manage: http://$serverip:$priport/ocp.php\n"
printf "=========================================================================\n"
cat /etc/vpssim/opcache.blacklist > /tmp/check_zendblacklist
sed -i '/wp-content/d' /tmp/check_zendblacklist
if [ ! "$(grep home /tmp/check_zendblacklist)" == "" ]; then
echo "=========================================================================" > /home/$mainsite/private_html/OP-Blacklist.txt
echo "Zend Opcache Black List - Created by VPSSIM " >> /home/$mainsite/private_html/OP-Blacklist.txt
echo "=========================================================================" >> /home/$mainsite/private_html/OP-Blacklist.txt
echo "" >> /home/$mainsite/private_html/OP-Blacklist.txt
cat /etc/vpssim/opcache.blacklist >> /home/$mainsite/private_html/OP-Blacklist.txt
cat > "/tmp/viewzendcacheblacklist" <<END	
sed -i 's/\/home\///g' /home/$mainsite/private_html/OP-Blacklist.txt
sed -i 's/\///g' /home/$mainsite/private_html/OP-Blacklist.txt
END
chmod +x /tmp/viewzendcacheblacklist
/tmp/viewzendcacheblacklist
rm -rf /tmp/viewzendcacheblacklist
sed -i '/wp-content/d' /home/$mainsite/private_html/OP-Blacklist.txt
else
echo "=========================================================================" > /home/$mainsite/private_html/OP-Blacklist.txt
echo "Zend Opcache Black List - Created by VPSSIM " >> /home/$mainsite/private_html/OP-Blacklist.txt
echo "=========================================================================" >> /home/$mainsite/private_html/OP-Blacklist.txt
echo "" >> /home/$mainsite/private_html/OP-Blacklist.txt
echo "Hien tai khong co website nao trong Zend Opcache Blacklist" >> /home/$mainsite/private_html/OP-Blacklist.txt
fi
printf "Blacklist: `cat /tmp/check_zendblacklist | wc -l` | Link View: http://$serverip:$priport/OP-Blacklist.txt\n"
printf "=========================================================================\n"
rm -rf /tmp/check_zendblacklist
PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
    1 ) /etc/vpssim/menu/opcache/vpssim-tat-opcache;;
    2 ) /etc/vpssim/menu/opcache/vpssim-opcache-change-size;;
    3) /etc/vpssim/menu/opcache/vpssim-them-website-vao-blacklist;;
    4) /etc/vpssim/menu/opcache/vpssim-xoa-website-khoi-blacklist;;
    5) /etc/vpssim/menu/opcache/vpssim-clear-opcache;;
    $(( ${#options[@]}+1 )) ) echo "";  clear && /bin/vpssim;;
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu";continue;;

    esac
done
