#!/bin/sh
. /home/vpssim.conf
prompt="Lua chon cua ban (6-Thoat):"
options=("Bat Zend Opcache" "Cau Hinh Zend Opcache" "Them Website Vao BlackList" "Xoa Website Khoi Blacklist" "Clear Zend OPcache")
printf "=========================================================================\n"
printf "                VPSSIM - Quan Ly VPS/Server by HostingAZ.VN \n"
printf "=========================================================================\n"
printf "                          Zend OPcache Manage \n"
printf "=========================================================================\n"
printf "                    Zend Opcache Current: Disable\n"
printf "=========================================================================\n"
printf "Zend Opcache Manage Link: http://$serverip:$priport/ocp.php\n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
    1 ) /etc/vpssim/menu/opcache/vpssim-bat-opcache;;
    2 ) /etc/vpssim/menu/opcache/vpssim-opcache-change-size;;
    3) /etc/vpssim/menu/opcache/vpssim-them-website-vao-blacklist;;
    4) /etc/vpssim/menu/opcache/vpssim-xoa-website-khoi-blacklist;;
    5) /etc/vpssim/menu/opcache/vpssim-clear-opcache;;
    
    $(( ${#options[@]}+1 )) ) echo "";  clear && /bin/vpssim;;
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu";continue;;

    esac
done
