#!/bin/bash 
. /home/vpssim.conf

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $3}')" == "stopped" ]; then
clear
echo "========================================================================= "
echo "Memcached dang disable tren server."
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "`systemctl is-active memcached.service`" == "active" ]; then
clear
echo "========================================================================= "
echo "Memcached dang disable tren server."
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
fi

if [ -f /etc/sysconfig/memcached ]; then
echo "========================================================================="
echo "Su dung chuc nang nay de cau hinh luong RAM toi da Memcached co the dung"
echo "-------------------------------------------------------------------------"
echo "RAM cho Memcached phai la so tu nhien nam trong khoang (20 - $(calc $( free -m | awk 'NR==2 {print $2}' )/7))."
echo "-------------------------------------------------------------------------"
echo -n "Nhap luong RAM toi da cho Memcached [ENTER]: " 
read memcacheram
if [ "$memcacheram" = "" ]; then
clear
echo "========================================================================="
echo "Ban nhap sai, vui long nhap lai "
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi

if ! [[ $memcacheram -ge 20 && $memcacheram -le $(calc $( free -m | awk 'NR==2 {print $2}' )/7)  ]] ; then  
clear
echo "========================================================================="
echo "$memcacheram khong dung!"
echo "-------------------------------------------------------------------------"
echo "phai la so tu nhien nam trong khoang (20 - $(calc $( free -m | awk 'NR==2 {print $2}' )/7))."
echo "-------------------------------------------------------------------------"
echo "Ban hay lam lai !"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi  
echo "-------------------------------------------------------------------------"
echo "Please wait ..."
sleep 1
rm -rf /etc/sysconfig/memcached
cat > "/etc/sysconfig/memcached" <<END
PORT="11211"
USER="memcached"
MAXCONN="10024"
CACHESIZE="$memcacheram"
OPTIONS=""
END
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service memcached restart
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
systemctl restart memcached.service
fi
clear
echo "========================================================================="
echo "Config thanh cong Memcached su dung $memcacheram MB RAM"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
clear
echo "========================================================================= "
echo "Khong phat hien Memcached tren VPS"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
