#!/bin/sh 
. /home/vpssim.conf

#
if [ ! -f /etc/cron.d/vpssim.code.cron ]; then
touch /etc/cron.d/vpssim.code.cron
fi

# Check VPSSIM Update
/etc/vpssim/menu/menucheck/check-vpssim-update
# Check nginx Update
#/etc/vpssim/menu/menucheck/check-nginx-update
/etc/vpssim/menu/menucheck/check-phpmyadmin-update
#/etc/vpssim/menu/menucheck/check-csf-on
# kiem tra dung luong dia con lai
#/etc/vpssim/menu/menucheck/check-disk-usage


rm -rf /tmp/*ip*
rm -rf /tmp/showthongbao 


#find /etc/vpssim/menu -type f -exec chmod 755 {} \;
prompt="Nhap lua chon cua ban (0-Backspace):"
options=( "Account Manager" "Advanced Features" "Extra Features" "Security/ Firewall" "Cache" "Update System" "Site Summary / Statistics" "Help" )

echo "========================================================================="
echo "                          ECHBAY-VPSSIM Menu                             "
echo "========================================================================="
# menu này dành cho centos 8, 9 -> chưa hoàn thiện lắm
echo "                Phien ban thu nghiem cho CentOS 8 & 9                    "
echo "========================================================================="

#
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in

	1) clear && /etc/vpssim/menu/centos9/option/account-manager-menu;;
    2) clear && /etc/vpssim/menu/centos9/option/advanced-features-menu;;
    3) clear && /etc/vpssim/menu/centos9/option/extra-features-menu;;
    4) clear && /etc/vpssim/menu/centos9/option/security-firewall-menu;;
    5) clear && /etc/vpssim/menu/centos9/option/cache-menu;;
    6) clear && /etc/vpssim/menu/centos9/option/update-upgrade-service-menu;;
    7) clear && /etc/vpssim/menu/centos9/option/site-summary-statistics;;
    8) clear && /etc/vpssim/menu/centos9/option/Help;;
	0) clear && cat /etc/motd && killall -g vpssim;; 
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac
done
 
