#!/bin/bash

#
cd ~
if [ ! -d /etc/vpssim/menu/tienich ]; then
echo "Create dir /etc/vpssim/menu/tienich"
mkdir -p /etc/vpssim/menu/tienich
chmod 755 /etc/vpssim/menu/tienich
chown -R root:root /etc/vpssim/menu/tienich
fi

#
cd ~
cd /etc/vpssim/menu/tienich
curl -sO https://raw.echbay.com/itvn9online/vpssim-free/master/script/vpssim/menu/tienich/update-wordpress-for-all-site-action.sh
cd ~

#
f="/etc/vpssim/menu/tienich/update-wordpress-for-all-site-action.sh"
#
if [ ! -f $f ]; then
echo "File not found! "$f
exit
fi

# b
chmod +x /etc/vpssim/menu/tienich/update-wordpress-for-all-site-action.sh

# Xóa tất cả các khoảng trắng ở đầu mỗi dòng.
sed -i -e "s/^[ \\\t]*//" $f

# Xóa tất cả các khoảng trắng ở cuối mỗi dòng.
sed -i -e "s/ *$//" $f

# Xóa các dòng trống
sed -i -e "/^$/d" $f

#
sed -i 's/\r//' $f

#
bash /etc/vpssim/menu/tienich/update-wordpress-for-all-site-action.sh
