#!/bin/bash 
if [ -f /etc/csf/csf.conf ]; then
printf "=========================================================================\n"
printf "CSF Firewall nen duoc cai dat de bao ve VPS/Server.\n"
echo "-------------------------------------------------------------------------"
read -r -p "Ban chac chan muon remove CSF Firewall? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait....";sleep 1
echo "Chuan bi remove CSF Firewall... "
sleep 1
yes | cp -rf /etc/csf/csf.conf /etc/vpssim/csf.conf_bak
cd /etc/csf
sh uninstall.sh
cd
clear
clear
echo "========================================================================= "
echo "Remove CSF Firewall thanh cong ! "

/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
;;
    *)
       clear 
echo "========================================================================= "
echo "Ban huy remove CSF FIREWALL."
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
        ;;
esac
clear 
echo "========================================================================= "
echo "Ban huy remove CSF FIREWALL"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
else
clear
echo "========================================================================= "
echo "VPS cua ban chua cai dat CSF Firewall ! "
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
exit
fi



