#!/bin/bash
#. /home/vpssim.conf

# lấy mật khẩu mysql thông qua phương thức này -> vì include file conf nó sẽ sinh ra đoạn bắt nhập mã -> không tiện lợi
DATABASE_PASS=$(cat /tmp/vpssim-mysqlrootpass)

#
echo "=========================================================================="
echo "Install MariaDB with root password: "$DATABASE_PASS
#sleep 2
sudo yum install -y mariadb-server mariadb

#
systemctl start mariadb
systemctl enable mariadb
#systemctl status mariadb

#
#sudo mysqladmin version

#mysql_secure_installation

#
mysqladmin -u root password "$DATABASE_PASS"
# Make sure that NOBODY can access the server without a password
#mysql -u root -p"$DATABASE_PASS" -e "UPDATE mysql.user SET Password=PASSWORD('$DATABASE_PASS') WHERE User='root'"
#mysql -u root -p"$DATABASE_PASS" -e "SET PASSWORD FOR 'root'@localhost = PASSWORD('$DATABASE_PASS')"
# Kill the anonymous users
mysql -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
mysql -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.user WHERE User=''"
# Kill off the demo database
mysql -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
# Make our changes take effect
mysql -u root -p"$DATABASE_PASS" -e "FLUSH PRIVILEGES"

#
rm -rf /tmp/vpssim-mysqlrootpass
